/*
 *  Programado por Gustavo Zimbrón
 *  www.zimbronapps.com 
 */
package arbolfractal;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints; 
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Zimbrón zimbronapps.com
 */
public class Arbol extends javax.swing.JFrame {

    private int xi;
    private int yi; 
    private final int tamanoi;
    private int anguloi;
    private int profundidadi;
    
    private Double sx = 1.0, sy = 1.0;

    /**
     * Creates new form Arbol
     */
    public Arbol() {
        initComponents();
        xi = jPanel1.getWidth() / 2;
        yi = jPanel1.getHeight();
        tamanoi = 50;
        anguloi = -90;
    }

    private void iniciar() {
        profundidadi = sliderprof.getValue();
        Graphics g = jPanel1.getGraphics();
        g.setColor(Color.black);
        g.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Dibujar(g, xi, yi, anguloi, profundidadi, tamanoi);
    }

    private void Dibujar(Graphics g, int x1, int y1, double angulo, int profundidad, int tamano) {
        if (profundidad == 0) {
            return;
        }
        Graphics2D g2 = (Graphics2D) g;
        g.setColor(Color.GREEN);
        g2.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);//Filtro antialiasing              

        int x2 = x1 + (int) (Math.cos(Math.toRadians(angulo)) * tamano * sx);
        int y2 = y1 + (int) (Math.sin(Math.toRadians(angulo)) * tamano * sy);
        g2.drawLine(x1, y1, x2, y2);
        Dibujar(g2, x2, y2, angulo - 20, profundidad - 1, (int) (tamano * .9));
        Dibujar(g2, x2, y2, angulo + 20, profundidad - 1, (int) (tamano * .9));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sliderprof = new javax.swing.JSlider();
        labelprof = new javax.swing.JLabel();
        trasladar = new javax.swing.JButton();
        escalar = new javax.swing.JButton();
        rotar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Árbol Fractal - Zimbronapps.com");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Árbol Fractal - zimbronapps.com");

        jButton1.setText("Dibujar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jLabel2.setText("Profundidad:");

        sliderprof.setMaximum(15);
        sliderprof.setMinimum(1);
        sliderprof.setValue(12);
        sliderprof.setFocusable(false);
        sliderprof.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderprofStateChanged(evt);
            }
        });

        labelprof.setText("12");

        trasladar.setText("Trasladar");
        trasladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasladarActionPerformed(evt);
            }
        });

        escalar.setText("Escalar");
        escalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalarActionPerformed(evt);
            }
        });

        rotar.setText("Rotar");
        rotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelprof, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderprof, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trasladar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escalar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sliderprof, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelprof)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(trasladar)
                        .addComponent(escalar)
                        .addComponent(rotar)))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sliderprofStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderprofStateChanged
        // TODO add your handling code here:
        labelprof.setText("" + sliderprof.getValue());
    }//GEN-LAST:event_sliderprofStateChanged

    private void trasladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasladarActionPerformed
        // TODO add your handling code here:
        String v = JOptionPane.showInputDialog("Ingresa coordenadas a trasladar: X,Y");
        if (v != null) {
            String[] vv = v.trim().split(",");
            int dx = Integer.valueOf(vv[0]);
            int dy = Integer.valueOf(vv[1]);
            xi += dx;
            yi += dy;
            iniciar();
        }
    }//GEN-LAST:event_trasladarActionPerformed

    private void escalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalarActionPerformed
        // TODO add your handling code here:
       String v = JOptionPane.showInputDialog("Ingresa escalamiento X,Y: 1 = 100%   .5 = 50%");
        if (v != null) {
            String[] vv = v.trim().split(",");
            sx *= Double.valueOf(vv[0]);
            sy *= Double.valueOf(vv[1]);
            iniciar();
        }
    }//GEN-LAST:event_escalarActionPerformed

    private void rotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarActionPerformed
        // TODO add your handling code here:
        String v = JOptionPane.showInputDialog("Angulo a rotar:");
        if (v != null) {
            int rota = Integer.valueOf(v);
            anguloi -= rota;
            iniciar();
        }

    }//GEN-LAST:event_rotarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton escalar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelprof;
    private javax.swing.JButton rotar;
    private javax.swing.JSlider sliderprof;
    private javax.swing.JButton trasladar;
    // End of variables declaration//GEN-END:variables
}
