package vista;

import acceso_datos.DAO_Encomienda;
import controlador.Control;
import javax.swing.JOptionPane;
import negocio.Encomienda;


/**
 *
 * @author manager
 */
public class DlgVender extends javax.swing.JDialog {

    private static final DAO_Encomienda dao_enmienda = new DAO_Encomienda();

    private long en_id;
    private String en_destinatario;
    private String en_direccion;
    private String en_tipo;
    private int en_entregadomicilio;
    private String en_tamano;
    private String en_remitente;


    /**
     * Creates new form NewJDialog
     *
     * @param inParent
     */
    public DlgVender(java.awt.Window inParent) {
        super(inParent, ModalityType.APPLICATION_MODAL);

        initComponents();
        MyInitComponents();

        en_id = 0;
        en_destinatario = "";
        en_direccion = "";
        en_tipo = "";
        en_entregadomicilio = 0;
        en_tamano = "";
        en_remitente = "";
    }


    /**
     * Inicializar componentes propios de la clase
     *
     */
    private void MyInitComponents() {

        final java.awt.Window me = this;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    Control.actionSalir(me);
                });
            }
        });

        txtId.requestFocus();
        Limpiar();
    }


    private void Limpiar() {
        txtId.setText("");
        txtDest.setText("");
        txtDir.setText("");
        txtRemitente.setText("");

        rbSobre.setSelected(true);
        rbPaquete.setSelected(false);

        cbxEntregaDir.setSelected(true);
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoEnc = new javax.swing.ButtonGroup();
        cbxTam = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        txtRemitente = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        txtDest = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        txtDir = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarID = new javax.swing.JButton();
        rbSobre = new javax.swing.JRadioButton();
        rbPaquete = new javax.swing.JRadioButton();
        cbxEntregaDir = new javax.swing.JCheckBox();
        label1 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Agregar");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Pequeño", "Mediano", "Grande" }));
        cbxTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTamActionPerformed(evt);
            }
        });
        getContentPane().add(cbxTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 313, -1, -1));

        jLabel2.setText("Destinatario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 116, -1, -1));

        label2.setText("Remitente:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 362, -1, -1));

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 179, -1, -1));
        getContentPane().add(txtRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 362, 251, -1));

        txtId.setEditable(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 56, 86, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 414, -1, -1));
        getContentPane().add(txtDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 110, 298, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 414, -1, -1));
        getContentPane().add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 173, 298, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jLabel4.setText("Tipo de encomienda:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 231, -1, -1));

        btnBuscarID.setText("Buscar ID");
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 56, -1, -1));

        btngTipoEnc.add(rbSobre);
        rbSobre.setText("Sobre");
        getContentPane().add(rbSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 229, -1, -1));

        btngTipoEnc.add(rbPaquete);
        rbPaquete.setText("Paquete");
        getContentPane().add(rbPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 253, -1, -1));

        cbxEntregaDir.setText("Entrega a domicilio");
        getContentPane().add(cbxEntregaDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 277, -1, -1));

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("REGISTRO DE ENCOMIENDA");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 10, -1, -1));

        jLabel5.setText("Tamaño:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 318, -1, -1));

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 62, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        setSize(new java.awt.Dimension(525, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTamActionPerformed

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        final java.awt.Window me = this;

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                (new DlgListar(me)).setVisible(true);

                Encomienda reg = DlgListar.getRegEnc();
                if (reg != null) {
                    txtId.setText(String.valueOf(reg.getEn_id()));
                    txtDest.setText(reg.getEn_destinatario());
                    txtDir.setText(reg.getEn_direccion());
                    switch (reg.getEn_tipo()) {
                        case "Sobre":
                            rbSobre.setSelected(true);
                            break;

                        case "Paquete":
                            rbPaquete.setSelected(true);
                            break;
                    }

                    cbxEntregaDir.setSelected(reg.getEn_entregadomicilio() != 0);

                    cbxTam.setSelectedItem(reg.getEn_tamano());

                    txtRemitente.setText(reg.getEn_remitente());
                }
            }
        });
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        en_id = 0;
        en_destinatario = "";
        en_direccion = "";
        en_tipo = "";
        en_entregadomicilio = 0;
        en_tamano = "";
        en_remitente = "";

        en_destinatario = txtDest.getText().trim().toUpperCase();
        if (en_destinatario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "DESTINATARIO INVALIDO");
            txtDest.requestFocus();
            return;
        }

        en_direccion = txtDir.getText().trim().toUpperCase();
        if (en_direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "DIRECCION INVALIDO");
            txtDir.requestFocus();
            return;
        }

        if (rbSobre.isSelected()) {
            en_tipo = "Sobre";
        } else if (rbPaquete.isSelected()) {
            en_tipo = "Paquete";
        } else {
            en_tipo = "";
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN TIPO DE PAQUETE");
            rbSobre.requestFocus();
            return;
        }

        en_entregadomicilio = cbxEntregaDir.isSelected() ? 1 : 0;

        int intTipoTam = cbxTam.getSelectedIndex();
        if (intTipoTam <= 0) {
            JOptionPane.showMessageDialog(this, "TIPO TAMAÑO INVALIDO");
            cbxTam.requestFocus();
            return;
        }

        en_tamano = (String) cbxTam.getSelectedItem();

        en_remitente = txtRemitente.getText().trim().toUpperCase();
        if (en_remitente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "REMITENTE INVALIDO");
            txtRemitente.requestFocus();
            return;
        }

        Encomienda reg = dao_enmienda.get(en_id);

        // Registro encontrado
        if (reg != null) {
            JOptionPane.showMessageDialog(this, "REGISTRO EXISTENTE, AGREGAR INVALIDO");
        } else {
            if (dao_enmienda.save(new Encomienda(en_id, en_destinatario, en_direccion, en_tipo, en_entregadomicilio, en_tamano, en_remitente))) {
                JOptionPane.showMessageDialog(this, "REGISTRO NUEVO, AGREGADO");
            }
            txtDest.requestFocus();
        }

        Limpiar();

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        en_id = 0;
        en_destinatario = "";
        en_direccion = "";
        en_tipo = "";
        en_entregadomicilio = 0;
        en_tamano = "";
        en_remitente = "";

        String strEn_id = txtId.getText().trim().toUpperCase();
        if (strEn_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID INVALIDO");
            txtId.requestFocus();
            return;
        }

        try {
            en_id = Long.parseLong(strEn_id);
        } catch (Exception inEx) {
            JOptionPane.showMessageDialog(this, "ID INVALIDO");
            txtId.requestFocus();
            return;
        }

        en_destinatario = txtDest.getText().trim().toUpperCase();
        if (en_destinatario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "DESTINATARIO INVALIDO");
            return;
        }

        en_direccion = txtDir.getText().trim().toUpperCase();
        if (en_direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "DIRECCION INVALIDO");
            return;
        }

        if (rbSobre.isSelected()) {
            en_tipo = "Sobre";
        } else if (rbPaquete.isSelected()) {
            en_tipo = "Paquete";
        } else {
            en_tipo = "";
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN TIPO DE PAQUETE");
            rbSobre.requestFocus();
            return;
        }

        en_entregadomicilio = cbxEntregaDir.isSelected() ? 1 : 0;

        int intTipoTam = cbxTam.getSelectedIndex();
        if (intTipoTam <= 0) {
            JOptionPane.showMessageDialog(this, "TIPO TAMAÑO INVALIDO");
            cbxTam.requestFocus();
            return;
        }

        switch (intTipoTam) {
            case 1:
                en_tamano = "Pequeño";
                break;

            case 2:
                en_tamano = "Mediano";
                break;

            case 3:
                en_tamano = "Grande";
                break;
        }

        en_remitente = txtRemitente.getText().trim().toUpperCase();
        if (en_remitente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "REMITENTE INVALIDO");
            txtRemitente.requestFocus();
            return;
        }

        Encomienda reg = dao_enmienda.get(en_id);

        // Registro encontrado
        if (reg != null) {
            reg.setEn_destinatario(en_destinatario);
            reg.setEn_direccion(en_direccion);
            reg.setEn_tipo(en_tipo);
            reg.setEn_entregadomicilio(en_entregadomicilio);
            reg.setEn_tamano(en_tamano);
            reg.setEn_remitente(en_remitente);
            if (dao_enmienda.update(reg)) {
                JOptionPane.showMessageDialog(this, "Registro modificado");
            } else {
                JOptionPane.showMessageDialog(this, "Error al tratar de modificar el Registro");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Registro NO encontrado");
        }

        Limpiar();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Control.actionSalir(this);
    }//GEN-LAST:event_btnSalirActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgVender dialog = new DlgVender(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup btngTipoEnc;
    private javax.swing.JCheckBox cbxEntregaDir;
    private javax.swing.JComboBox<String> cbxTam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JRadioButton rbPaquete;
    private javax.swing.JRadioButton rbSobre;
    private javax.swing.JTextField txtDest;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtRemitente;
    // End of variables declaration//GEN-END:variables
}
