package com.manager.presentacion;

/**
 *
 * @author manager
 */
public class dlgAcercaDe extends javax.swing.JDialog {

    /**
     * Creates new form dlgAcercaDe
     *
     * @param parent
     */
    public dlgAcercaDe(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de Ventas de Negocio");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setText("Programa para gestionar las Ventas de un negocio (bodega, ferretería, farmacia, abarrotes, entre otros) utilizando ESTRUCTURAS Dinámicas (LISTA O LISTAS CIRCULARES O PILAS O COLAS). \n\nConsiderando estructuras dinámicas que sirvieron para representar a: cliente, producto, vendedor, factura y un detalle_factura\n.");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
