package serviciobarberia.vista;

import static java.awt.Dialog.DEFAULT_MODALITY_TYPE;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import serviciobarberia.modelo.Bitacora;
import serviciobarberia.modelo.BitacoraCRUD;
import serviciobarberia.modelo.Cliente;
import serviciobarberia.modelo.ClienteCRUD;
import serviciobarberia.modelo.Servicio;
import serviciobarberia.modelo.ServicioCRUD;

/**
 *
 * @author manager
 */
public class BitacoraVerTabla extends javax.swing.JDialog {

    /**
     * Creates new form BitacoraVerTabla
     */
    public BitacoraVerTabla(java.awt.Window parent) {
        super(parent, DEFAULT_MODALITY_TYPE);
        initComponents();
        myInitComponents();
    }

    public void myInitComponents() {

        // Esto se utiliza mas adelante, para pasar esta Win como parametro en el "windowClosing"
        final java.awt.Window me = this;

        // Creación del listener, qie sera ejecutado una vez que se quiera cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    ActionExit(me);
                });
            }
        });

    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            actualizarTabla();
        }
        super.setVisible(b);
    }

    private void ActionExit(final java.awt.Window inWin) {
        inWin.setVisible(false);
        inWin.dispose();

        final Window parent = inWin.getOwner();
        if (parent != null) {
            parent.setVisible(true);
        } else {
            System.exit(0);
        }
    }

    private void actualizarTabla() {

        // Borrar la tabla maestra
        tabla.clearSelection();
        final DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        ClienteCRUD cCrud = new ClienteCRUD();
        ServicioCRUD sCrud = new ServicioCRUD();
        BitacoraCRUD bCrud = new BitacoraCRUD();
        ArrayList<Bitacora> list = bCrud.findAll();

        for (Bitacora item : list) {

            Object[] datos = new Object[4];

            String cnombre;
            Optional<Cliente> oc = cCrud.read(item.getIdcliente());
            if (oc.isPresent()) {
                cnombre = oc.get().getNombre();
            } else {
                cnombre = "No encontado";
            }

            String snombre;
            Optional<Servicio> os = sCrud.read(item.getIdservicio());
            if (os.isPresent()) {
                snombre = os.get().getNombre();
            } else {
                snombre = "No encontado";
            }

            datos[0] = item.getIdbitacora();
            datos[1] = cnombre;
            datos[2] = snombre;
            datos[3] = item.getTexto();

            model.addRow(datos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        btnConsultar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0));
        btnModificar = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Bitacoras");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Control", "Cliente", "Servicio", "Texto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(50);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(0).setMaxWidth(50);
            tabla.getColumnModel().getColumn(1).setMinWidth(200);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabla.getColumnModel().getColumn(1).setMaxWidth(200);
            tabla.getColumnModel().getColumn(2).setMinWidth(200);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabla.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        getContentPane().add(jScrollPane1);
        getContentPane().add(filler3);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler2);

        btnConsultar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setMaximumSize(new java.awt.Dimension(120, 30));
        btnConsultar.setMinimumSize(new java.awt.Dimension(120, 30));
        btnConsultar.setPreferredSize(new java.awt.Dimension(120, 30));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar);
        jPanel1.add(filler1);

        btnModificar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        jPanel1.add(filler4);

        btnEliminar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(120, 30));
        btnEliminar.setMinimumSize(new java.awt.Dimension(120, 30));
        btnEliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (tabla.getSelectedRow() != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

            Integer idbitacora = (Integer) modelo.getValueAt(tabla.getSelectedRow(), 0);

            java.awt.EventQueue.invokeLater(() -> {
                (new BitacoraModificar(this, idbitacora, false)).setVisible(true);
            });

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una bitacora");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (tabla.getSelectedRow() != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

            Integer idbitacora = (Integer) modelo.getValueAt(tabla.getSelectedRow(), 0);

            java.awt.EventQueue.invokeLater(() -> {
                (new BitacoraModificar(this, idbitacora, true)).setVisible(true);
            });

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una bitacora");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tabla.getSelectedRow() != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

            Integer idbitacora = (Integer) modelo.getValueAt(tabla.getSelectedRow(), 0);

            java.awt.EventQueue.invokeLater(() -> {
                (new BitacoraEliminar(this, idbitacora)).setVisible(true);
            });

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una bitacora");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            BitacoraVerTabla dialog = new BitacoraVerTabla(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
