/*
 * Todos los derechos reservados por CAPIP Sistemas C.A., Venezuela
 * RIF J-407111787
 * capipsistemas@gmail.com, baba.orere@gmail.com
 * @2016, 2017, 2018
 */
package com.principal.bancos;

import com.principal.capipsistema.Propiedades;
import com.principal.capipsistema.UserTrack;
import com.principal.connection.ConnCapip;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * @author Capip Sistemas C.A.
 */
public final class BancoCuentaEliminar extends javax.swing.JFrame {

    private final java.awt.Window parent;

    /**
     * Creates new form ecuenta
     *
     * @param inparent
     */
    public BancoCuentaEliminar(final java.awt.Window inparent) {
        super();
        initComponents();
        parent = inparent;
        setOwnBehavior();
        setCompBehavior();
        setStartConditions();
    }

    /**
     * Para Reubicar la ventana al ser visualizada
     *
     * @param inb
     */
    @Override
    public void setVisible(boolean inb) {
        // Para mostrar la ventana en el tope de la pantalla
        if (inb) {
            setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) / 2, 10);
        }
        super.setVisible(inb);
    }

    /**
     * Establece el comportamiento de la presente Ventana Rev 21/09/2016
     */
    private void setOwnBehavior() {
        try {
            UserTrack.trackUser(getClass().getName(), "INIT", getTitle());
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
            logger.error(inex);
        }
        setTitle(Propiedades.CAPIP_SISTEMAS + " - " + getTitle() + " - " + Propiedades.CAPIP_CLIENTE_RAZONSOCIAL);
        // Establecer acción al cerrar ventana
        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                actSalir();
            }
        });
        // Para salir con la tecla ESC
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");
        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                actSalir();
            }
        });
    }

    /**
     * Rev /10/2016
     */
    private void setCompBehavior() {
    }

    /**
     * Rev /10/2016
     */
    private void setStartConditions() {
        mostrardatosbancos();
    }

    /**
     * Rev 25/11/2016
     */
    void mostrardatosbancos() {
        final DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("BANCO");
        modelo.addColumn("CUENTA");
        jTablebancos.setModel(modelo);
        final Object[] datos = new Object[2];
        try {
            final ResultSet rs = ConnCapip.getInstance().executeQuery("SELECT * FROM bancos ORDER BY banco, cuenta ASC");
            while (rs.next()) {
                datos[0] = rs.getString("banco");
                datos[1] = rs.getString("cuenta");
                modelo.addRow(datos);
            }
            jTablebancos.setModel(modelo);
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
            logger.error(inex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebancos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ELIMINAR CUENTAS BANCARIAS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnEliminar.setBackground(java.awt.SystemColor.inactiveCaption);
        // NOI18N
        btnEliminar.setFont(new java.awt.Font("Arial", 2, 16));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, 40));
        btnSalir.setBackground(java.awt.SystemColor.inactiveCaption);
        // NOI18N
        btnSalir.setFont(new java.awt.Font("Arial", 2, 16));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 110, 40));
        // NOI18N
        jLabel1.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel1.setText("       SELECCIONE LA CUENTA BANCARIA A ELIMINAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 502, -1));
        // NOI18N
        jTablebancos.setFont(new java.awt.Font("Arial", 3, 12));
        jTablebancos.setForeground(new java.awt.Color(0, 51, 102));
        jTablebancos.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { {}, {}, {}, {}, {}, {}, {}, {}, {}, {} }, new String[] {}));
        jTablebancos.setSelectionBackground(new java.awt.Color(175, 204, 125));
        jScrollPane1.setViewportView(jTablebancos);
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 576, 210));
        // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo azul 22.png")));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 620, 330));
        pack();
        setLocationRelativeTo(null);
    }

    // </editor-fold>//GEN-END:initComponents
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnSalirActionPerformed
        actSalir();
    }

    //GEN-LAST:event_btnSalirActionPerformed
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTablebancos.getSelectedRow();
        if (fila < 0) {
            return;
        }
        String cod = jTablebancos.getValueAt(fila, 0).toString();
        try {
            final PreparedStatement pst = ConnCapip.getInstance().getConnection().prepareStatement("DELETE FROM bancos WHERE  cuenta='" + cod + "'");
            int op = JOptionPane.showConfirmDialog(this, "Si existe algun dato sin guardar " + "se perderán.\n ¿Seguro desea Eliminar?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.OK_OPTION) {
                pst.executeUpdate();
            }
            mostrardatosbancos();
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
            logger.error(inex);
        }
    }

    //GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Rev 25/11/2016
     */
    private void actSalir() {
        if (parent != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    parent.setVisible(true);
                    dispose();
                }
            });
        } else {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new BancoCuentaEliminar(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;

    private javax.swing.JButton btnSalir;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTable jTablebancos;

    // End of variables declaration//GEN-END:variables
    Connection cn = ConnCapip.getInstance().getConnection();

    private static final Logger logger = LogManager.getLogger(BancoCuentaEliminar.class);
}
