package com.tayrona;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;

/**
 *
 * @author manager
 */
public final class AppFrame extends javax.swing.JFrame {

    private final static String REGULAR = "empleadoRegular.bin";
    private final static String VENTA = "empleadoVenta.bin";

    private static ArrayList<Empleado> empList;

    static {
        empList = new ArrayList<>();
    }

    public static ArrayList<Empleado> getEmpList() {
        return empList;
    }

    public static void addEmp(Empleado inEmpleado) {
        empList.add(inEmpleado);
    }

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        // Aqui se procede a crear los componentes graficos, varios de la GUI
        initComponents();

        // Aqui se procede a crear los componentes propios de la clase, los funcionales de la aplicación
        myInitComponents();
    }

    public void myInitComponents() {

        // Esto se utiliza mas adelante, para pasar esta Win como parametro en el "windowClosing"
        final java.awt.Window me = this;

        // Creación del listener, quien sera ejecutado una vez que se quiera cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    Controller.actionSalir(me);
                });
            }
        });

        empList = new ArrayList<>();

        // Leer archivo
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(REGULAR));

            Object aux;
            while ((aux = ois.readObject()) != null) {
                empList.add((EmpRegular) aux);
            }

        } catch (Exception ex) {
        }

        // Leer archivo
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(VENTA));

            Object aux;
            while ((aux = ois.readObject()) != null) {
                empList.add((EmpVenta) aux);
            }

        } catch (Exception ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel1 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnRegistroDialog = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnConsultaDialog = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TAYRONA");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        pnlTitulo.setMaximumSize(new java.awt.Dimension(2147483647, 70));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(452, 70));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(800, 70));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Empleados");
        pnlTitulo.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitulo);

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(36, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jEditorPane1.setEditable(false);
        jEditorPane1.setText("Aplicación que permite el registro de información sobre un Empleado, en una Base de Datos, \ny realizar unos cálculos correspondientes a pago de nómina y bonificaciones, \ndependiendo del contexto de la contratación y funciones desempeñadas.");
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel2.add(filler1, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(filler2, java.awt.BorderLayout.LINE_END);
        jPanel2.add(filler3, java.awt.BorderLayout.LINE_START);
        jPanel2.add(filler4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler6);

        btnRegistroDialog.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        btnRegistroDialog.setText("Registro");
        btnRegistroDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDialogActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroDialog);
        jPanel1.add(filler7);

        btnConsultaDialog.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        btnConsultaDialog.setText("Consulta");
        btnConsultaDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaDialogActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultaDialog);
        jPanel1.add(filler5);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDialogActionPerformed
        Controller.actionRegistrarDialog(this);
    }//GEN-LAST:event_btnRegistroDialogActionPerformed

    private void btnConsultaDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaDialogActionPerformed
        Controller.actionTableDialog(this);
    }//GEN-LAST:event_btnConsultaDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaDialog;
    private javax.swing.JButton btnRegistroDialog;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
