package com.tayrona;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 */
public final class RegistroDialog extends javax.swing.JDialog {

    private final static String REGULAR = "empleadoRegular.bin";
    private final static String VENTA = "empleadoVenta.bin";

    /**
     * Creates new form RegistroDialog
     *
     * @param inWin
     */
    public RegistroDialog(final java.awt.Window inWin) {
        super(inWin, DEFAULT_MODALITY_TYPE);

        // Aqui se procede a crear los componentes graficos, varios de la GUI
        initComponents();

        // Aqui se procede a crear los componentes propios de la clase, los funcionales de la aplicación
        myInitComponents();
    }

    public void myInitComponents() {

        // Esto se utiliza mas adelante, para pasar esta Win como parametro en el "windowClosing"
        final java.awt.Window me = this;

        // Creación del listener, quien sera ejecutado una vez que se quiera cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    Controller.actionSalir(me);
                });
            }
        });

        // Llenar los Combos
        cmbSexo.addItem(SexoEnum.FEMENINO);
        cmbSexo.addItem(SexoEnum.MASCULINO);
        cmbSexo.setSelectedIndex(-1);

        cmbEdoCivil.addItem(EdoCivilEnum.SOLTERO);
        cmbEdoCivil.addItem(EdoCivilEnum.CASADO);
        cmbEdoCivil.addItem(EdoCivilEnum.DIVORCIADO);
        cmbEdoCivil.addItem(EdoCivilEnum.VIUDO);
        cmbEdoCivil.setSelectedIndex(-1);

        cmbGradoEsc.addItem(GradoEscolaridadEnum.BASICA);
        cmbGradoEsc.addItem(GradoEscolaridadEnum.MEDIA);
        cmbGradoEsc.addItem(GradoEscolaridadEnum.UNIVERSITARIA);
        cmbGradoEsc.addItem(GradoEscolaridadEnum.POSTGRADO);
        cmbGradoEsc.setSelectedIndex(-1);

        cmbEPS.addItem(EpsEnum.CAFESALUD);
        cmbEPS.addItem(EpsEnum.COMPENSAR);
        cmbEPS.addItem(EpsEnum.SALUD_COLMENA);
        cmbEPS.addItem(EpsEnum.SALUD_TOTAL);
        cmbEPS.addItem(EpsEnum.SANITAS);
        cmbEPS.addItem(EpsEnum.UNIMEC);
        cmbEPS.setSelectedIndex(-1);

        cmbCajaComp.addItem(CajaCompEnum.COLSUBSIDIO);
        cmbCajaComp.addItem(CajaCompEnum.COMBARRANQUILLA);
        cmbCajaComp.addItem(CajaCompEnum.COMFABOY);
        cmbCajaComp.addItem(CajaCompEnum.COMFAMA);
        cmbCajaComp.addItem(CajaCompEnum.COMFAMILIAR_CAMACOL);
        cmbCajaComp.setSelectedIndex(-1);

        cmbTipoCont.addItem(TipoContratoEnum.NOMINA);
        cmbTipoCont.addItem(TipoContratoEnum.SERVICIO);
        cmbTipoCont.addItem(TipoContratoEnum.VENTA);
        cmbTipoCont.setSelectedIndex(-1);

        cmbCategoria.addItem(CategoriaEnum.COORDINACION);
        cmbCategoria.addItem(CategoriaEnum.OFICINA);
        cmbCategoria.addItem(CategoriaEnum.SERVICIOS_GENERALES);
        cmbCategoria.addItem(CategoriaEnum.VENTAS);
        cmbCategoria.addItem(CategoriaEnum.GERENCIA);
        cmbCategoria.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtNumHijos = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        cmbGradoEsc = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        cmbEPS = new javax.swing.JComboBox<>();
        cmbEdoCivil = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAhorro = new javax.swing.JTextField();
        cmbTipoCont = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtMetaVentas = new javax.swing.JTextField();
        txtPorcBonificacion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        jLabel18 = new javax.swing.JLabel();
        cmbCajaComp = new javax.swing.JComboBox<>();
        pnlComandos = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnRegistrar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        btnCancelar = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tayrona");
        setResizable(false);

        pnlTitulo.setMaximumSize(new java.awt.Dimension(800, 75));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(800, 75));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(800, 75));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE EMPLEADO");
        pnlTitulo.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.NORTH);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("IDENTIFICACIÓN:");
        jLabel2.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOMBRE:");
        jLabel3.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("FECHA DE NACIMIENTO:");
        jLabel4.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("SEXO:");
        jLabel5.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ESTADO CIVIL:");
        jLabel6.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("NÚMERO DE HIJOS:");
        jLabel7.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("GRADO DE ESCOLARIDAD:");
        jLabel8.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("EPS:");
        jLabel9.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);
        jLabel9.getAccessibleContext().setAccessibleName("EPS");

        txtIdentificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdentificacion.setMaximumSize(new java.awt.Dimension(150, 25));
        txtIdentificacion.setMinimumSize(new java.awt.Dimension(150, 25));
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(txtIdentificacion, gridBagConstraints);

        txtNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNombre.setMaximumSize(new java.awt.Dimension(150, 25));
        txtNombre.setMinimumSize(new java.awt.Dimension(150, 25));
        txtNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(txtNombre, gridBagConstraints);

        txtFechaNac.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtFechaNac.setMaximumSize(new java.awt.Dimension(150, 25));
        txtFechaNac.setMinimumSize(new java.awt.Dimension(150, 25));
        txtFechaNac.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(txtFechaNac, gridBagConstraints);

        txtNumHijos.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNumHijos.setMaximumSize(new java.awt.Dimension(150, 25));
        txtNumHijos.setMinimumSize(new java.awt.Dimension(150, 25));
        txtNumHijos.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(txtNumHijos, gridBagConstraints);

        cmbSexo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbSexo.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbSexo.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbSexo.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(cmbSexo, gridBagConstraints);

        cmbGradoEsc.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbGradoEsc.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbGradoEsc.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbGradoEsc.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(cmbGradoEsc, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(filler3, gridBagConstraints);

        cmbEPS.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbEPS.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbEPS.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbEPS.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(cmbEPS, gridBagConstraints);

        cmbEdoCivil.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbEdoCivil.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbEdoCivil.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbEdoCivil.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(cmbEdoCivil, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 0));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("CAJA DE COMPENSACIÓN:");
        jLabel10.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel10, gridBagConstraints);

        txtSalario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtSalario.setMaximumSize(new java.awt.Dimension(150, 25));
        txtSalario.setMinimumSize(new java.awt.Dimension(150, 25));
        txtSalario.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(txtSalario, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("SALARIO:");
        jLabel11.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("AHORRO:");
        jLabel12.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel12, gridBagConstraints);

        txtAhorro.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtAhorro.setMaximumSize(new java.awt.Dimension(150, 25));
        txtAhorro.setMinimumSize(new java.awt.Dimension(150, 25));
        txtAhorro.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(txtAhorro, gridBagConstraints);

        cmbTipoCont.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbTipoCont.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbTipoCont.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbTipoCont.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(cmbTipoCont, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("TIPO CONTRATACIÓN:");
        jLabel13.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("CATEGORÍA");
        jLabel14.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel14, gridBagConstraints);

        cmbCategoria.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbCategoria.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbCategoria.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbCategoria.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(cmbCategoria, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("META DE VENTAS:");
        jLabel16.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel16, gridBagConstraints);

        txtMetaVentas.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtMetaVentas.setMaximumSize(new java.awt.Dimension(150, 25));
        txtMetaVentas.setMinimumSize(new java.awt.Dimension(150, 25));
        txtMetaVentas.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(txtMetaVentas, gridBagConstraints);

        txtPorcBonificacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPorcBonificacion.setMaximumSize(new java.awt.Dimension(150, 25));
        txtPorcBonificacion.setMinimumSize(new java.awt.Dimension(150, 25));
        txtPorcBonificacion.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(txtPorcBonificacion, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("PORC. BONIFICACIÓN:");
        jLabel17.setPreferredSize(new java.awt.Dimension(185, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        jPanel3.add(filler4, gridBagConstraints);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("solo si el empleado es de Ventas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(jLabel18, gridBagConstraints);

        cmbCajaComp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbCajaComp.setMaximumSize(new java.awt.Dimension(150, 25));
        cmbCajaComp.setMinimumSize(new java.awt.Dimension(150, 25));
        cmbCajaComp.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(cmbCajaComp, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pnlComandos.setMaximumSize(new java.awt.Dimension(800, 50));
        pnlComandos.setMinimumSize(new java.awt.Dimension(800, 50));
        pnlComandos.setPreferredSize(new java.awt.Dimension(800, 50));
        pnlComandos.setLayout(new javax.swing.BoxLayout(pnlComandos, javax.swing.BoxLayout.LINE_AXIS));
        pnlComandos.add(filler2);

        btnRegistrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setMaximumSize(new java.awt.Dimension(125, 30));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(125, 30));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(125, 30));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlComandos.add(btnRegistrar);
        pnlComandos.add(filler1);

        btnCancelar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(125, 30));
        btnCancelar.setMinimumSize(new java.awt.Dimension(125, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(125, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlComandos.add(btnCancelar);
        pnlComandos.add(filler5);

        getContentPane().add(pnlComandos, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Controller.actionSalir(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        // Leer y validar los campos
        String identificacion;
        identificacion = txtIdentificacion.getText().trim().toUpperCase();
        if ((identificacion.length() < 4) || (identificacion.length() > 12)) {
            System.out.println("Identificacion invalida");
            return;
        }

        String nombre;
        nombre = txtNombre.getText().trim().toUpperCase();
        if ((nombre.length() <= 0) || (nombre.length() > 128)) {
            System.out.println("Identificacion invalida, 0 < nombre <= 128");
            return;
        }

        LocalDate fechaNac;
        String strFechaNac;
        strFechaNac = txtFechaNac.getText().trim();

        try {
            fechaNac = LocalDate.parse(strFechaNac, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fecha invalida, formato dd-MM-yyyy");
            return; // Salir
        }

        SexoEnum sexo;
        if (cmbSexo.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Sexo invalido, debe seleccionar");
            return; // Salir
        }
        sexo = (SexoEnum) cmbSexo.getSelectedItem();

        EdoCivilEnum edoCivil;
        if (cmbEdoCivil.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Estado Civil invalido, debe seleccionar");
            return; // Salir
        }
        edoCivil = (EdoCivilEnum) cmbEdoCivil.getSelectedItem();

        Integer numHijos;
        String strNumHijos;
        strNumHijos = txtNumHijos.getText().trim();

        try {
            numHijos = Integer.parseInt(strNumHijos);
        } catch (Exception inEx) {
            JOptionPane.showMessageDialog(this, "Número de hijos invalido, debe ser un número entero positivo");
            return; // Salir
        }

        if (numHijos < 0) {
            JOptionPane.showMessageDialog(this, "Número de hijos invalido, debe ser un número entero positivo");
            return; // Salir
        }

        GradoEscolaridadEnum gradoEsc;
        if (cmbGradoEsc.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Grado Escolaridad invalido, debe seleccionar");
            return; // Salir
        }
        gradoEsc = (GradoEscolaridadEnum) cmbGradoEsc.getSelectedItem();

        EpsEnum epsEnum;
        if (cmbEPS.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "EPS invalido, debe seleccionar");
            return; // Salir
        }
        epsEnum = (EpsEnum) cmbEPS.getSelectedItem();

        CajaCompEnum cajaComp;
        if (cmbCajaComp.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Caja Compensación nvalido, debe seleccionar");
            return; // Salir
        }
        cajaComp = (CajaCompEnum) cmbCajaComp.getSelectedItem();

        Integer salario;
        String strSalario;
        strSalario = txtSalario.getText().trim();

        try {
            salario = Integer.parseInt(strSalario);
        } catch (Exception inEx) {
            JOptionPane.showMessageDialog(this, "Salario invalido, debe ser un número entero positivo");
            return; // Salir
        }

        if (salario < 0) {
            JOptionPane.showMessageDialog(this, "Salario invalido, debe ser un número entero positivo");
            return; // Salir
        }

        Integer ahorro;
        String strAhorro;
        strAhorro = txtAhorro.getText().trim();

        try {
            ahorro = Integer.parseInt(strAhorro);
        } catch (Exception inEx) {
            JOptionPane.showMessageDialog(this, "Ahorro invalido, debe ser un número positivo entero");
            return; // Salir
        }

        if (ahorro < 0) {
            JOptionPane.showMessageDialog(this, "Salario invalido, debe ser un número entero positivo");
            return; // Salir
        }

        TipoContratoEnum tipoContrato;
        if (cmbTipoCont.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Tipo de Contrato invalido, debe seleccionar");
            return; // Salir
        }
        tipoContrato = (TipoContratoEnum) cmbTipoCont.getSelectedItem();

        CategoriaEnum categoria;
        if (cmbCategoria.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Categoría invalida, debe seleccionar");
            return; // Salir
        }
        categoria = (CategoriaEnum) cmbCategoria.getSelectedItem();

        if (categoria.equals(CategoriaEnum.VENTAS)) {
            Integer metaVentas;
            String strMetaVentas;
            strMetaVentas = txtMetaVentas.getText().trim();

            try {
                metaVentas = Integer.parseInt(strMetaVentas);
            } catch (Exception inEx) {
                JOptionPane.showMessageDialog(this, "Meta en ventas invalido, debe ser un número positivo entero");
                return; // Salir
            }

            if (metaVentas < 0) {
                JOptionPane.showMessageDialog(this, "Meta en ventas invalido, debe ser un número entero positivo");
                return; // Salir
            }

            Integer porcNonificacion;
            String strPorcNonificacion;
            strPorcNonificacion = txtPorcBonificacion.getText().trim();

            try {
                porcNonificacion = Integer.parseInt(strPorcNonificacion);
            } catch (Exception inEx) {
                JOptionPane.showMessageDialog(this, "Porcentaje de Bonificación invalido, debe ser un número positivo entero");
                return; // Salir
            }

            if ((porcNonificacion <= 0) || (porcNonificacion >= 100)) {
                JOptionPane.showMessageDialog(this, "Porcentaje de Bonificación invalido, 0 < % < 100");
                return; // Salir
            }

            // Crear el registro de empleado
            Empleado registro = new EmpVenta(identificacion, nombre, fechaNac, sexo, edoCivil, numHijos, gradoEsc, epsEnum,
                cajaComp, salario, ahorro, tipoContrato, categoria, metaVentas, porcNonificacion);

            // Agregar el empleado a la lista de Empleados, guardada en el JFrame
            AppFrame.addEmp(registro);

        } else {
            txtMetaVentas.setText("");
            txtPorcBonificacion.setText("");

            // Crear el registro de empleado
            Empleado registro = new EmpRegular(identificacion, nombre, fechaNac, sexo, edoCivil, numHijos, gradoEsc, epsEnum,
                cajaComp, salario, ahorro, tipoContrato, categoria);

            // Agregar el empleado a la lista de Empleados, guardada en el JFrame
            AppFrame.addEmp(registro);
        }

        JOptionPane.showMessageDialog(this, "Empleado agregado con exito");

        // Guardar al Archivo
        try {
            ObjectOutputStream oosRegular = new ObjectOutputStream(new FileOutputStream(REGULAR));
            ObjectOutputStream oosVenta = new ObjectOutputStream(new FileOutputStream(VENTA));

            List<Empleado> list = AppFrame.getEmpList();
            for (int i = 0; i < list.size(); i++) {
                Empleado reg = list.get(i);

                if (reg instanceof EmpRegular) {
                    oosRegular.writeObject(reg);
                } else {
                    oosVenta.writeObject(reg);
                }

            }

            oosRegular.close();
            oosVenta.close();

        } catch (Exception inEx) {
        }

        // Salir
        btnCancelar.doClick();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistroDialog dialog = new RegistroDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<CajaCompEnum> cmbCajaComp;
    private javax.swing.JComboBox<com.tayrona.CategoriaEnum> cmbCategoria;
    private javax.swing.JComboBox<EpsEnum> cmbEPS;
    private javax.swing.JComboBox<EdoCivilEnum> cmbEdoCivil;
    private javax.swing.JComboBox<GradoEscolaridadEnum> cmbGradoEsc;
    private javax.swing.JComboBox<SexoEnum> cmbSexo;
    private javax.swing.JComboBox<TipoContratoEnum> cmbTipoCont;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlComandos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtAhorro;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtMetaVentas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumHijos;
    private javax.swing.JTextField txtPorcBonificacion;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
