/*
 * Todos los derechos reservados por CAPIP Sistemas C.A., Venezuela
 * RIF J-407111787
 * capipsistemas@gmail.com, baba.orere@gmail.com
 * @2016, 2017, 2018
 */
package capipsistema;

import account_module.main.AccountingMain;
import bancos.BancosContabilidad;
import causados.Causado;
import compromisos.Compromiso;
import configuracion.Configuracion;
import impuestos.ImpuestoRetencion;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelos.UserModel;
import pagos.PagoOrden;
import presupuesto.PptoInstitucion;
import reportes.ReporteSel;

/**
 * Ventana Principal de la aplicación, utiliza el patrón de diseño Singleton
 *
 * @author CAPIP Sistemas C.A.
 *
 */
public final class FrmPrincipal extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Hace accesible la única instacia de clase Rev 21/09/2016
     *
     * @return
     */
    public static FrmPrincipal getInstance() {
        return FrmPrincipal.NewSingletonHolder.INSTANCE;
    }

    /**
     * Clase auxiliar, para implementar el Singlenton Rev 21/09/2016
     *
     */
    private static class NewSingletonHolder {

        private static final FrmPrincipal INSTANCE = new FrmPrincipal();
    }

    /**
     * Creates new form panel Rev 25/11/2016
     *
     */
    private FrmPrincipal() {

        super();
        initComponents();

        setOwnBehavior();
        setCompBehavior();
        setStartConditions();
    }

    /**
     * Para Reubicar la ventana al ser visualizada Rev 25/11/2016
     *
     * @param inb
     */
    @Override
    public void setVisible(boolean inb) {
        // Para mostrar la ventana en el tope de la pantalla
        if (inb) {
            setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) / 2, 10);
        }

        super.setVisible(inb);
    }

    /**
     * Establece el comportamiento de la presente Ventana Rev 25/11/2016
     *
     */
    private void setOwnBehavior() {
        try {
            UserTrack.trackUser(getClass().getName(), "INIT", getTitle());
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
        }

        setTitle(CapipPropiedades.CAPIP_SISTEMAS + " - " + getTitle() + " - " + CapipPropiedades.CAPIP_CLIENTE_RAZONSOCIAL);

        // Establecer acción al cerrar ventana
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                btnSalir.doClick();
            }
        });
    }

    /**
     * Rev 15/11/2016
     *
     * Establece el comportamiento de los componentes de la Ventana Rev 21/09/2016
     */
    private void setCompBehavior() {
    }

    /**
     * Establece las condiciones iniciales de la Ventana Rev 25/11/2016
     */
    private void setStartConditions() {
        lblUser.setText(UserPassIn.getUser());
        lblUserName.setText(UserPassIn.getUserName());
        lblSession.setText(String.valueOf(UserPassIn.getIdSession()));

        java.awt.EventQueue.invokeLater(btnSalir::requestFocusInWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSession = new javax.swing.JLabel();
        btnPresupuesto = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCausado = new javax.swing.JButton();
        btnRetenciones = new javax.swing.JButton();
        btnPago = new javax.swing.JButton();
        btnBanco = new javax.swing.JButton();
        btnConfiguacion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCompromisos = new javax.swing.JButton();
        btncontab = new javax.swing.JButton();
        btnRequerimiento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setMinimumSize(new java.awt.Dimension(1150, 730));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("USUARIO: ");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 70, -1));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setText("User");
        lblUser.setMaximumSize(new java.awt.Dimension(0, 20));
        lblUser.setMinimumSize(new java.awt.Dimension(0, 20));
        lblUser.setPreferredSize(new java.awt.Dimension(0, 20));
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 250, 20));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserName.setText("UserName");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 280, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SESIÓN: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 60, -1));

        lblSession.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSession.setText("Sesión");
        lblSession.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSession.setMaximumSize(new java.awt.Dimension(80, 14));
        lblSession.setMinimumSize(new java.awt.Dimension(40, 14));
        lblSession.setPreferredSize(new java.awt.Dimension(40, 14));
        getContentPane().add(lblSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 130, 20));

        btnPresupuesto.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnPresupuesto.setForeground(new java.awt.Color(0, 51, 51));
        btnPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/presupuesto 2.png"))); // NOI18N
        btnPresupuesto.setText("PRESUPUESTO");
        btnPresupuesto.setBorder(null);
        btnPresupuesto.setBorderPainted(false);
        btnPresupuesto.setContentAreaFilled(false);
        btnPresupuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresupuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPresupuesto.setIconTextGap(-3);
        btnPresupuesto.setMaximumSize(new java.awt.Dimension(105, 87));
        btnPresupuesto.setMinimumSize(new java.awt.Dimension(105, 87));
        btnPresupuesto.setPreferredSize(new java.awt.Dimension(105, 87));
        btnPresupuesto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/presupuesto 3.png"))); // NOI18N
        btnPresupuesto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/presupuesto 1.png"))); // NOI18N
        btnPresupuesto.setVerifyInputWhenFocusTarget(false);
        btnPresupuesto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPresupuesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 125, 80));

        btnReportes.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 51, 51));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes 2.png"))); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setIconTextGap(-3);
        btnReportes.setOpaque(true);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes 3.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes 1.png"))); // NOI18N
        btnReportes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 120, 80));

        btnCausado.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCausado.setForeground(new java.awt.Color(0, 51, 51));
        btnCausado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gasto causado 2.png"))); // NOI18N
        btnCausado.setText("GASTO CAUSADO");
        btnCausado.setBorder(null);
        btnCausado.setBorderPainted(false);
        btnCausado.setContentAreaFilled(false);
        btnCausado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCausado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCausado.setIconTextGap(-3);
        btnCausado.setMaximumSize(new java.awt.Dimension(117, 73));
        btnCausado.setMinimumSize(new java.awt.Dimension(117, 73));
        btnCausado.setPreferredSize(new java.awt.Dimension(117, 73));
        btnCausado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gasto causado 3.png"))); // NOI18N
        btnCausado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gasto causado 1.png"))); // NOI18N
        btnCausado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCausado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCausado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCausadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCausado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 125, 80));

        btnRetenciones.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnRetenciones.setForeground(new java.awt.Color(0, 51, 51));
        btnRetenciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iva  2.png"))); // NOI18N
        btnRetenciones.setText("RETENCIONES");
        btnRetenciones.setBorder(null);
        btnRetenciones.setBorderPainted(false);
        btnRetenciones.setContentAreaFilled(false);
        btnRetenciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetenciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetenciones.setIconTextGap(-3);
        btnRetenciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iva  3.png"))); // NOI18N
        btnRetenciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iva 1 (2).png"))); // NOI18N
        btnRetenciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRetenciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetencionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetenciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 125, 80));

        btnPago.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnPago.setForeground(new java.awt.Color(0, 51, 51));
        btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden de pago 2.png"))); // NOI18N
        btnPago.setText("ORDEN PAGO");
        btnPago.setBorder(null);
        btnPago.setBorderPainted(false);
        btnPago.setContentAreaFilled(false);
        btnPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPago.setIconTextGap(-3);
        btnPago.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden de pago 3.png"))); // NOI18N
        btnPago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden de pago 1.png"))); // NOI18N
        btnPago.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 125, 80));

        btnBanco.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnBanco.setForeground(new java.awt.Color(0, 51, 51));
        btnBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco 2.png"))); // NOI18N
        btnBanco.setText("BANCO");
        btnBanco.setBorder(null);
        btnBanco.setBorderPainted(false);
        btnBanco.setContentAreaFilled(false);
        btnBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBanco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanco.setIconTextGap(-3);
        btnBanco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco 3.png"))); // NOI18N
        btnBanco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco 1.png"))); // NOI18N
        btnBanco.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBanco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 125, 80));

        btnConfiguacion.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnConfiguacion.setForeground(new java.awt.Color(0, 51, 51));
        btnConfiguacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion 2.png"))); // NOI18N
        btnConfiguacion.setText("CONFIGURACION");
        btnConfiguacion.setBorder(null);
        btnConfiguacion.setBorderPainted(false);
        btnConfiguacion.setContentAreaFilled(false);
        btnConfiguacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguacion.setIconTextGap(-3);
        btnConfiguacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion 3.png"))); // NOI18N
        btnConfiguacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion 1.png"))); // NOI18N
        btnConfiguacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConfiguacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfiguacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 120, 80));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 51, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir 2.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setIconTextGap(-3);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir3.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir1.png"))); // NOI18N
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 550, 90, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo programa.png"))); // NOI18N
        jLabel1.setIconTextGap(-3);
        jLabel1.setPreferredSize(new java.awt.Dimension(1020, 640));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1160, 570));

        btnCompromisos.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCompromisos.setForeground(new java.awt.Color(0, 51, 51));
        btnCompromisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Compromiso 2.png"))); // NOI18N
        btnCompromisos.setText("COMPROMISOS");
        btnCompromisos.setBorder(null);
        btnCompromisos.setBorderPainted(false);
        btnCompromisos.setContentAreaFilled(false);
        btnCompromisos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompromisos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompromisos.setIconTextGap(-3);
        btnCompromisos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Compromiso 3.png"))); // NOI18N
        btnCompromisos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Compromiso 1.png"))); // NOI18N
        btnCompromisos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCompromisos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompromisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompromisosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompromisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 125, 80));

        btncontab.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btncontab.setForeground(new java.awt.Color(0, 51, 51));
        btncontab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad2.png"))); // NOI18N
        btncontab.setText("CONTABILIDAD");
        btncontab.setBorder(null);
        btncontab.setBorderPainted(false);
        btncontab.setContentAreaFilled(false);
        btncontab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncontab.setIconTextGap(-3);
        btncontab.setMaximumSize(new java.awt.Dimension(121, 73));
        btncontab.setMinimumSize(new java.awt.Dimension(121, 73));
        btncontab.setOpaque(true);
        btncontab.setPreferredSize(new java.awt.Dimension(121, 73));
        btncontab.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad3.png"))); // NOI18N
        btncontab.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad1.png"))); // NOI18N
        btncontab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btncontab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncontab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontabActionPerformed(evt);
            }
        });
        getContentPane().add(btncontab, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 130, 80));

        btnRequerimiento.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnRequerimiento.setForeground(new java.awt.Color(0, 51, 51));
        btnRequerimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/requerimiento2.png"))); // NOI18N
        btnRequerimiento.setText("REQUERIMIENTO");
        btnRequerimiento.setBorder(null);
        btnRequerimiento.setBorderPainted(false);
        btnRequerimiento.setContentAreaFilled(false);
        btnRequerimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRequerimiento.setIconTextGap(-3);
        btnRequerimiento.setMaximumSize(new java.awt.Dimension(123, 73));
        btnRequerimiento.setMinimumSize(new java.awt.Dimension(123, 73));
        btnRequerimiento.setOpaque(true);
        btnRequerimiento.setPreferredSize(new java.awt.Dimension(123, 73));
        btnRequerimiento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/requerimiento3.png"))); // NOI18N
        btnRequerimiento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/requerimiento1.png"))); // NOI18N
        btnRequerimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRequerimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequerimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 7, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo azul 22.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Rev 25/11/2016
     *
     * @param evt
     */
    private void btnPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresupuestoActionPerformed
        if (UserModel.isPpto(UserPassIn.getIdUser())) {
            final java.awt.Window me = this;
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new PptoInstitucion(me).setVisible(true);
                    me.setVisible(false);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnPresupuestoActionPerformed

    /**
     * Rev 25/11/2016
     *
     * @param evt
     */
    private void btnCausadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCausadoActionPerformed
        if (UserModel.isCau(UserPassIn.getIdUser())) {
            final java.awt.Window me = this;

            java.awt.EventQueue.invokeLater(() -> {
                new Causado(me).setVisible(true);
                me.setVisible(false);
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnCausadoActionPerformed

    /**
     * Rev 26/11/2016
     *
     * @param evt
     */
    private void btnRetencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetencionesActionPerformed
        java.awt.Window me = this;

        if (UserModel.isImp(UserPassIn.getIdUser())) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new ImpuestoRetencion(me).setVisible(true);
                    me.setVisible(false);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnRetencionesActionPerformed

    /**
     * Rev 26/11/2016
     *
     * @param evt
     */
    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        if (UserModel.isPago(UserPassIn.getIdUser())) {
            final java.awt.Window me = this;

            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new PagoOrden(me).setVisible(true);
                    me.setVisible(false);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnPagoActionPerformed

    /**
     * Rev 26/11/2016
     *
     * @param evt
     */
    private void btnBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoActionPerformed

        if (UserModel.isBanco(UserPassIn.getIdUser())) {
            java.awt.Window me = this;

            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new BancosContabilidad(me).setVisible(true);
                    me.setVisible(false);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnBancoActionPerformed

    private void btnConfiguacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguacionActionPerformed
        if (UserModel.isCfg(UserPassIn.getIdUser())) {
            java.awt.Window me = this;
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Configuracion(me).setVisible(true);
                    me.setVisible(false);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnConfiguacionActionPerformed

    /**
     * Rev 21/09/2016
     *
     * @param evt
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        actSalir();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Finalizar completamente la Aplicación
     *
     * Rev 21/09/2016
     *
     */
    private void actSalir() {
        try {
            UserTrack.trackUser(getClass().getName(), "SALIR", getTitle());
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
        }

        System.exit(0);
    }

    private void btnCompromisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompromisosActionPerformed
        java.awt.Window me = this;

        if (UserModel.isCompr(UserPassIn.getIdUser())) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Compromiso(me).setVisible(true);
                    me.setVisible(false);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnCompromisosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        java.awt.Window me = this;

        if (UserModel.isRpt(UserPassIn.getIdUser())) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new ReporteSel(me).setVisible(true);
                    me.setVisible(false);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimientoActionPerformed
        java.awt.Window me = this;

        if (UserModel.isRequerim(UserPassIn.getIdUser())) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    JOptionPane.showMessageDialog(null, "Este modulo se encuantra en Construcción");
                    // me.setVisible(false);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequerimientoActionPerformed

    private void btncontabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontabActionPerformed
        if (UserModel.isPpto(UserPassIn.getIdUser())) {
            final java.awt.Window me = this;
            java.awt.EventQueue.invokeLater(() -> {
                new AccountingMain(me).setVisible(true);
            });

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }
    }//GEN-LAST:event_btncontabActionPerformed

    private static String toStr(byte[] inin) {
        final StringBuilder sb = new StringBuilder();

        for (int i = 0; i < inin.length; i++) {
            sb.append(String.valueOf(inin[i]));
        }

        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                FrmPrincipal.getInstance().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanco;
    private javax.swing.JButton btnCausado;
    private javax.swing.JButton btnCompromisos;
    private javax.swing.JButton btnConfiguacion;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPresupuesto;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnRequerimiento;
    private javax.swing.JButton btnRetenciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btncontab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSession;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables

}
