package com.manager;

import java.math.BigInteger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author manager
 */
public final class dlgAppMain extends javax.swing.JDialog {

    // Aqui se guarda la ventana contenedora, el Padre/Madre
    private final java.awt.Frame owner;

    private Cola<Telefono> miCola;

// **********************************************************************************************

    /**
     *
     */
    /**
     * Creates new form dlgAppMain
     *
     * @param parent
     */
    public dlgAppMain(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.owner = parent;
        MyInitComponents();
    }


    /**
     * Inicializar componentes propios de la clase
     *
     */
    private void MyInitComponents() {

        final javax.swing.JDialog me = this;
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                Salir();
            }
        });

        this.miCola = new Cola();

        limpiarEntradas();
        mostrarDatos();

        txtNom.requestFocus();
    }


    /**
     * Acciones para cerrar la aplicacion
     *
     */
    private void Salir() {
        this.setVisible(false);
        this.dispose();

        if (owner != null) {
            owner.setVisible(false);
            owner.dispose();
        }

        System.exit(0);
    }


    private void mostrarDatos() {

        if ((miCola == null) || miCola.vacia()) {
            limpiarEntradas();
            return;
        }

        DefaultListModel model = new DefaultListModel();
        lstList.setModel(model);

        final int tam = miCola.getTam();
        for (int i = 0; i < tam; i++) {

            Telefono elem = miCola.eliminar();

            model.addElement(elem.toString());

            // Encolar de nuevo el elemento
            // Como se trata de un for fijo, al final obtenemos los elementos ordenados de la misma forma  
            miCola.insertar(elem);
        }

        txtTam.setText(String.valueOf(miCola.getTam()));
        txtIni.setText(miCola.getInicio().toString());
        txtFin.setText(miCola.getFinal().toString());

        txtNom.requestFocus();
    }


    private void limpiarEntradas() {
        txtTam.setText("");
        txtIni.setText("");
        txtFin.setText("");
        txtNom.setText("");
        txtTelf.setText("");

        txtNom.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        lblIni = new javax.swing.JLabel();
        txtIni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelf = new javax.swing.JTextField();
        txtFin = new javax.swing.JTextField();
        lblFin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ejemplo de una Cola, implementada con lista doblemente encadenada");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 350));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tamaño");
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtTam.setEditable(false);
        txtTam.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTam.setMinimumSize(new java.awt.Dimension(150, 30));
        txtTam.setPreferredSize(new java.awt.Dimension(150, 30));
        txtTam.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(txtTam, gridBagConstraints);

        lblIni.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblIni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIni.setText("Inicio");
        lblIni.setMinimumSize(new java.awt.Dimension(80, 30));
        lblIni.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(lblIni, gridBagConstraints);

        txtIni.setEditable(false);
        txtIni.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIni.setMinimumSize(new java.awt.Dimension(200, 30));
        txtIni.setPreferredSize(new java.awt.Dimension(250, 30));
        txtIni.setRequestFocusEnabled(false);
        txtIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIniMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(txtIni, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        txtNom.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNom.setMinimumSize(new java.awt.Dimension(200, 30));
        txtNom.setPreferredSize(new java.awt.Dimension(250, 30));
        txtNom.setRequestFocusEnabled(false);
        txtNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(txtNom, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Teléfono");
        jLabel4.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtTelf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTelf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelf.setMinimumSize(new java.awt.Dimension(200, 30));
        txtTelf.setPreferredSize(new java.awt.Dimension(250, 30));
        txtTelf.setRequestFocusEnabled(false);
        txtTelf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelfMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(txtTelf, gridBagConstraints);

        txtFin.setEditable(false);
        txtFin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFin.setMinimumSize(new java.awt.Dimension(200, 30));
        txtFin.setPreferredSize(new java.awt.Dimension(250, 30));
        txtFin.setRequestFocusEnabled(false);
        txtFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFinMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(txtFin, gridBagConstraints);

        lblFin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFin.setText("Fin");
        lblFin.setMinimumSize(new java.awt.Dimension(80, 30));
        lblFin.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(lblFin, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnEliminar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar el Inicio de la Cola");
        btnEliminar.setMinimumSize(new java.awt.Dimension(160, 35));
        btnEliminar.setPreferredSize(new java.awt.Dimension(160, 35));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        jPanel2.add(btnEliminar, gridBagConstraints);

        btnInsertar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setToolTipText("Insertar a la Cola");
        btnInsertar.setMinimumSize(new java.awt.Dimension(160, 35));
        btnInsertar.setPreferredSize(new java.awt.Dimension(160, 35));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        jPanel2.add(btnInsertar, gridBagConstraints);

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setMinimumSize(new java.awt.Dimension(160, 35));
        btnSalir.setPreferredSize(new java.awt.Dimension(160, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        jPanel2.add(btnSalir, gridBagConstraints);

        getContentPane().add(jPanel2);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(250, 150));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(250, 150));

        lstList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstList.setEnabled(false);
        jScrollPane2.setViewportView(lstList);

        getContentPane().add(jScrollPane2);

        setSize(new java.awt.Dimension(827, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        // Lista no ha sido creada
        if ((miCola == null) || miCola.vacia()) {
            JOptionPane.showMessageDialog(null, "La cola esta Vacia");
            limpiarEntradas();
            txtNom.requestFocus();
            return;
        }

        Telefono aux = miCola.eliminar();

        mostrarDatos();

        txtNom.setText(String.valueOf(aux.getNombre()));
        txtTelf.setText(String.valueOf(aux.getNumero()));

        txtNom.requestFocus();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed

        // Lista no ha sido creada
        if (miCola == null) {
            JOptionPane.showMessageDialog(null, "La cola no ha sido Creada");
            limpiarEntradas();
            txtNom.requestFocus();
            return;
        }

        String nombre = txtNom.getText().trim().toUpperCase();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "*** VALOR INVALIDO ***");
            txtNom.requestFocus();
            return;
        }

        String strNumero = txtTelf.getText().trim().toUpperCase();

        if (strNumero.length() != 9) {
            JOptionPane.showMessageDialog(this, "*** VALOR INVALIDO ***");
            txtTelf.requestFocus();
            return;
        }

        // Solo para verificar que es un Entero valido        
        try {
            BigInteger foo = new BigInteger(strNumero);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "*** VALOR INVALIDO ***");
            txtTelf.requestFocus();
            return;
        }

        miCola.insertar(new Telefono(nombre, strNumero));

        limpiarEntradas();
        mostrarDatos();
        txtNom.requestFocus();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void txtIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIniMouseClicked
        txtNom.requestFocus();
    }//GEN-LAST:event_txtIniMouseClicked

    private void txtNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomMouseClicked
        txtNom.requestFocus();
    }//GEN-LAST:event_txtNomMouseClicked

    private void txtTelfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelfMouseClicked
        txtTelf.requestFocus();
    }//GEN-LAST:event_txtTelfMouseClicked

    private void txtFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFinMouseClicked
        txtNom.requestFocus();
    }//GEN-LAST:event_txtFinMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                (new dlgAppMain(new javax.swing.JFrame())).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblIni;
    private javax.swing.JList<String> lstList;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtIni;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTam;
    private javax.swing.JTextField txtTelf;
    // End of variables declaration//GEN-END:variables

}
