package com.manager;

import java.awt.Container;
import java.awt.Rectangle;
import java.util.Iterator;
import java.util.List;
import java.util.TreeSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelos.BinarySearchTree;
import modelos.NumComplejo;
import modelos.Tree2Graphics;


/**
 *
 * @author manager
 */
public class DlgArbol extends javax.swing.JDialog {

    private BinarySearchTree<NumComplejo> myTreeTDA;
    private TreeSet<NumComplejo> myTreeSet;


    /**
     * Creates new form DlgCola
     *
     * @param parent
     */
    public DlgArbol(java.awt.Window parent) {
        super(parent, DEFAULT_MODALITY_TYPE);
        initComponents();
        MyInitComponents();
    }


    /**
     * Inicializar componentes propios de la clase
     *
     */
    private void MyInitComponents() {

        myTreeTDA = new BinarySearchTree();
        myTreeSet = new TreeSet<>();

        final javax.swing.JDialog me = this;
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                Salir();
            }
        });

        Limpiar();
    }


    private void Limpiar() {
        txtReX.setText("");
        txtImY.setText("");

        lstTreeSet.setModel(new DefaultListModel());
        lstTreeSet.setModel(new DefaultListModel());
    }


    private void MostrarDatos() {
        txtReX.setText("");
        txtImY.setText("");

        btnInOrder.doClick();

        DefaultListModel modelTreeSet = new DefaultListModel();
        lstTreeSet.setModel(modelTreeSet);

        Iterator<NumComplejo> iterator = myTreeSet.descendingIterator();

        modelTreeSet.addElement("Java TreeSet");

        while (iterator.hasNext()) {
            modelTreeSet.addElement(iterator.next());
        }

    }


    private void Salir() {
        setVisible(false);
        dispose();

        Container parent = getParent();
        if (parent != null) {
            parent.setVisible(true);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlG = new javax.swing.JPanel();
        pnl = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtImY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnPreOrder = new javax.swing.JButton();
        btnInOrder = new javax.swing.JButton();
        btnPostOrder = new javax.swing.JButton();
        txtReX = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTreeSet = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTDA = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TDA ARbol");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Árbol Binario de Búsqueda - Números Complejos ordenados por su Módulo");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setMaximumSize(new java.awt.Dimension(900, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(661, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 25));
        jPanel1.add(jLabel4);

        pnlG.setLayout(new java.awt.BorderLayout());

        pnl.setBackground(new java.awt.Color(204, 255, 204));
        pnlG.add(pnl, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlG);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Re, X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        txtImY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtImY.setMaximumSize(new java.awt.Dimension(25, 2147483647));
        txtImY.setMinimumSize(new java.awt.Dimension(25, 20));
        txtImY.setPreferredSize(new java.awt.Dimension(25, 20));
        txtImY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(txtImY, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Im. Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        btnAdd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setMaximumSize(new java.awt.Dimension(65, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(65, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(65, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(btnAdd, gridBagConstraints);

        btnDel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDel.setText("Del");
        btnDel.setMaximumSize(new java.awt.Dimension(65, 30));
        btnDel.setMinimumSize(new java.awt.Dimension(65, 30));
        btnDel.setPreferredSize(new java.awt.Dimension(65, 30));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(btnDel, gridBagConstraints);

        btnPreOrder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPreOrder.setText("Pre");
        btnPreOrder.setMaximumSize(new java.awt.Dimension(65, 30));
        btnPreOrder.setMinimumSize(new java.awt.Dimension(65, 30));
        btnPreOrder.setPreferredSize(new java.awt.Dimension(65, 30));
        btnPreOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(btnPreOrder, gridBagConstraints);

        btnInOrder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnInOrder.setText("In");
        btnInOrder.setMaximumSize(new java.awt.Dimension(65, 30));
        btnInOrder.setMinimumSize(new java.awt.Dimension(65, 30));
        btnInOrder.setPreferredSize(new java.awt.Dimension(65, 30));
        btnInOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(btnInOrder, gridBagConstraints);

        btnPostOrder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPostOrder.setText("Post");
        btnPostOrder.setMaximumSize(new java.awt.Dimension(65, 30));
        btnPostOrder.setMinimumSize(new java.awt.Dimension(65, 30));
        btnPostOrder.setPreferredSize(new java.awt.Dimension(65, 30));
        btnPostOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(btnPostOrder, gridBagConstraints);

        txtReX.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtReX.setMaximumSize(new java.awt.Dimension(25, 2147483647));
        txtReX.setMinimumSize(new java.awt.Dimension(25, 20));
        txtReX.setPreferredSize(new java.awt.Dimension(25, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(txtReX, gridBagConstraints);

        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBuscar.setText("Bus.");
        btnBuscar.setMaximumSize(new java.awt.Dimension(65, 30));
        btnBuscar.setMinimumSize(new java.awt.Dimension(65, 30));
        btnBuscar.setPreferredSize(new java.awt.Dimension(65, 30));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(btnBuscar, gridBagConstraints);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        jPanel5.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 22));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 400));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(150, 22));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(150, 131));

        lstTreeSet.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstTreeSet);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5);

        jPanel2.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 22));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(150, 22));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 131));

        lstTDA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstTDA);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        setSize(new java.awt.Dimension(1010, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {

            int reX;
            try {
                reX = Integer.parseInt(txtReX.getText().trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Valor real INVALIDO");
                txtReX.requestFocus();
                return;
            }

            int imY;
            try {
                imY = Integer.parseInt(txtImY.getText().trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Valor imaginario INVALIDO");
                txtImY.requestFocus();
                return;
            }

            NumComplejo nc = new NumComplejo(reX, imY);
            myTreeTDA.add(nc);
            myTreeSet.add(nc);

            Rectangle r = pnl.getBounds();
            this.pnlG.remove(pnl);
            this.pnl = new Tree2Graphics(myTreeTDA);
            pnl.setBounds(r);

            this.pnlG.add(this.pnl, java.awt.BorderLayout.CENTER);
            pnlG.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR \n" + e.toString());
        }

        Limpiar();
        MostrarDatos();

        txtReX.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {

            int reX;
            try {
                reX = Integer.parseInt(txtReX.getText().trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Valor real INVALIDO");
                txtReX.requestFocus();
                return;
            }

            int imY;
            try {
                imY = Integer.parseInt(txtImY.getText().trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Valor imaginario INVALIDO");
                txtImY.requestFocus();
                return;
            }

            NumComplejo nc = new NumComplejo(reX, imY);

            myTreeTDA.borrar(nc);
            myTreeSet.remove(nc);

            Rectangle r = pnl.getBounds();
            this.pnlG.remove(pnl);
            this.pnl = new Tree2Graphics(myTreeTDA);
            pnl.setBounds(r);

            this.pnlG.add(this.pnl, java.awt.BorderLayout.CENTER);
            pnlG.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR \n" + e.toString());
        }

        Limpiar();
        MostrarDatos();

        txtReX.requestFocus();

    }//GEN-LAST:event_btnDelActionPerformed

    private void btnPreOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrderActionPerformed
        DefaultListModel modelTDA = new DefaultListModel();
        lstTDA.setModel(modelTDA);

        List<NumComplejo> listTDA = myTreeTDA.preOrden();

        listTDA.forEach((dato) -> {
            modelTDA.addElement(dato.toString());
        });

    }//GEN-LAST:event_btnPreOrderActionPerformed

    private void btnInOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrderActionPerformed

        DefaultListModel modelTDA = new DefaultListModel();
        lstTDA.setModel(modelTDA);

        List<NumComplejo> listTDA = myTreeTDA.inOrden();

        listTDA.forEach((dato) -> {
            modelTDA.addElement(dato.toString());
        });

    }//GEN-LAST:event_btnInOrderActionPerformed

    private void btnPostOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrderActionPerformed
        DefaultListModel modelTDA = new DefaultListModel();
        lstTDA.setModel(modelTDA);

        List<NumComplejo> listTDA = myTreeTDA.postOrden();

        listTDA.forEach((dato) -> {
            modelTDA.addElement(dato.toString());
        });
    }//GEN-LAST:event_btnPostOrderActionPerformed

    private void txtImYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImYActionPerformed
        btnAdd.doClick();
    }//GEN-LAST:event_txtImYActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {

            int reX;
            try {
                reX = Integer.parseInt(txtReX.getText().trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Valor real INVALIDO");
                txtReX.requestFocus();
                return;
            }

            int imY;
            try {
                imY = Integer.parseInt(txtImY.getText().trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Valor imaginario INVALIDO");
                txtImY.requestFocus();
                return;
            }

            NumComplejo nc = new NumComplejo(reX, imY);

            if (myTreeTDA.Contains(nc)) {
                JOptionPane.showMessageDialog(this, "Número complejo ENCONTRADO: " + nc.toString());
            } else {
                JOptionPane.showMessageDialog(this, "Número complejo NO encontrado: " + nc.toString());
            }

            txtReX.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR \n" + e.toString());
        }

        Limpiar();
        MostrarDatos();

        txtReX.requestFocus();

    }//GEN-LAST:event_btnBuscarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgArbol dialog = new DlgArbol(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnInOrder;
    private javax.swing.JButton btnPostOrder;
    private javax.swing.JButton btnPreOrder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstTDA;
    private javax.swing.JList<String> lstTreeSet;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnlG;
    private javax.swing.JTextField txtImY;
    private javax.swing.JTextField txtReX;
    // End of variables declaration//GEN-END:variables
}
