package com.webapp.grafosangre;

import java.awt.Window;
import javax.swing.DefaultListModel;

/**
 *
 */
public final class DialogGrafica extends javax.swing.JDialog {

    private int matAdy[][];

    private PanelCanvas pnlCanvas;

    /**
     * Creates new form DialogGrafica
     *
     * @param inWin
     */
    public DialogGrafica(final java.awt.Window inWin) {

        // Llamar al constructor Padre
        super(inWin, ModalityType.APPLICATION_MODAL);

        // Aqui se procede a crear los componentes graficos, varios de la GUI
        initComponents();

        // Aqui se procede a crear los componentes propios de la clase, los funcionales de la aplicación
        myInitComponents();
    }

    public void myInitComponents() {

        // Esto se utiliza mas adelante, para pasar esta Win como parametro en el "windowClosing"
        final java.awt.Window me = this;

        // Creación del listener, qie sera ejecutado una vez que se quiera cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    ActionSalir(me);
                });
            }
        });

        // Crear la matriz
        matAdy = new int[4][4];

        // llenar la matriz de ceros
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                matAdy[i][j] = 0;
                tblMatAdy.setValueAt(0, j, j);
            }
        }

        /*
            Establecer los valores iniciales de la matriz
         */
        // Sangre tipo A
        matAdy[0][0] = 1; // puede darse a si mismo
        matAdy[0][2] = 1; // puede darse a al tipo AB

        // Sangre tipo B
        matAdy[1][1] = 1; // puede darse a si mismo
        matAdy[1][2] = 1; // puede darse a al tipo AB

        // Sangre tipo AB
        matAdy[2][2] = 1; // puede darse a si mismo

        // Sangre tipo O
        matAdy[3][0] = 1; // puede darse al tipo A
        matAdy[3][1] = 1; // puede darse al tipo B
        matAdy[3][2] = 1; // puede darse al tipo AB
        matAdy[3][3] = 1; // puede darse a si mismo

        // copiar los valores a la tabla
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                tblMatAdy.setValueAt(matAdy[i][j], i, j);
            }
        }

        // actualizar la matriz, en el panel
        // es necesario hacer un cast, para tener acceso al metodo "setMatAdy"
        ((PanelCanvas) pnlGrafica).setMatAdy(matAdy);
    }

    // Se utilizar para graficar al hacer visible la Ventana,
    // con los datos que esten cargados en la tabla
    @Override
    public void setVisible(boolean hacerVisible) {
        super.setVisible(hacerVisible);

        if (hacerVisible) {
            actionGraficar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlGrafica = new PanelCanvas();
        pnlDatos = new javax.swing.JPanel();
        pnlDatosTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMatrizAdyacencia = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatAdy = new javax.swing.JTable();
        pnlComandos = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(350, 0), new java.awt.Dimension(350, 0), new java.awt.Dimension(350, 0));
        btnGraficar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        btnOk = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVerAdy = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Matriz de Adyacencia y Graficar");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        pnlGrafica.setBackground(new java.awt.Color(0, 0, 0));
        pnlGrafica.setPreferredSize(new java.awt.Dimension(600, 200));

        javax.swing.GroupLayout pnlGraficaLayout = new javax.swing.GroupLayout(pnlGrafica);
        pnlGrafica.setLayout(pnlGraficaLayout);
        pnlGraficaLayout.setHorizontalGroup(
            pnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnlGraficaLayout.setVerticalGroup(
            pnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(pnlGrafica);

        pnlDatos.setLayout(new javax.swing.BoxLayout(pnlDatos, javax.swing.BoxLayout.PAGE_AXIS));

        pnlDatosTitulo.setMaximumSize(new java.awt.Dimension(600, 30));
        pnlDatosTitulo.setMinimumSize(new java.awt.Dimension(600, 30));
        pnlDatosTitulo.setPreferredSize(new java.awt.Dimension(600, 30));
        pnlDatosTitulo.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MATRIZ DE ADYACENCIA");
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 30));
        pnlDatosTitulo.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnlDatos.add(pnlDatosTitulo);

        pnlMatrizAdyacencia.setBackground(new java.awt.Color(0, 51, 51));
        pnlMatrizAdyacencia.setMaximumSize(new java.awt.Dimension(600, 150));
        pnlMatrizAdyacencia.setMinimumSize(new java.awt.Dimension(600, 150));
        pnlMatrizAdyacencia.setPreferredSize(new java.awt.Dimension(600, 150));
        pnlMatrizAdyacencia.setLayout(new javax.swing.BoxLayout(pnlMatrizAdyacencia, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(40, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(40, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 150));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(filler3);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A");
        jLabel3.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("B");
        jLabel4.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AB");
        jLabel5.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("O");
        jLabel6.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jLabel6);

        pnlMatrizAdyacencia.add(jPanel1);

        tblMatAdy.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tblMatAdy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "A", "B", "AB", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMatAdy.setGridColor(new java.awt.Color(51, 0, 51));
        tblMatAdy.setMaximumSize(new java.awt.Dimension(300, 120));
        tblMatAdy.setMinimumSize(new java.awt.Dimension(300, 120));
        tblMatAdy.setRowHeight(30);
        tblMatAdy.setRowSelectionAllowed(false);
        tblMatAdy.setShowGrid(true);
        jScrollPane1.setViewportView(tblMatAdy);
        if (tblMatAdy.getColumnModel().getColumnCount() > 0) {
            tblMatAdy.getColumnModel().getColumn(0).setResizable(false);
            tblMatAdy.getColumnModel().getColumn(1).setResizable(false);
            tblMatAdy.getColumnModel().getColumn(2).setResizable(false);
            tblMatAdy.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlMatrizAdyacencia.add(jScrollPane1);

        pnlDatos.add(pnlMatrizAdyacencia);

        jPanel2.add(pnlDatos);

        pnlComandos.setMaximumSize(new java.awt.Dimension(600, 30));
        pnlComandos.setMinimumSize(new java.awt.Dimension(600, 30));
        pnlComandos.setPreferredSize(new java.awt.Dimension(600, 30));
        pnlComandos.setLayout(new javax.swing.BoxLayout(pnlComandos, javax.swing.BoxLayout.LINE_AXIS));
        pnlComandos.add(filler2);

        btnGraficar.setBackground(new java.awt.Color(102, 255, 102));
        btnGraficar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnGraficar.setForeground(new java.awt.Color(0, 0, 0));
        btnGraficar.setText("Graficar");
        btnGraficar.setMaximumSize(new java.awt.Dimension(95, 25));
        btnGraficar.setMinimumSize(new java.awt.Dimension(95, 25));
        btnGraficar.setPreferredSize(new java.awt.Dimension(95, 25));
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        pnlComandos.add(btnGraficar);
        pnlComandos.add(filler1);

        btnOk.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnOk.setForeground(new java.awt.Color(0, 0, 0));
        btnOk.setText("Ok");
        btnOk.setMaximumSize(new java.awt.Dimension(85, 25));
        btnOk.setMinimumSize(new java.awt.Dimension(85, 25));
        btnOk.setPreferredSize(new java.awt.Dimension(85, 25));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlComandos.add(btnOk);

        jPanel2.add(pnlComandos);

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 0));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lstVerAdy.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Vértices", "Adyacentes", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstVerAdy);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        setSize(new java.awt.Dimension(760, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        ActionSalir(this);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed

        actionGraficar();
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogGrafica dialog = new DialogGrafica(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnOk;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstVerAdy;
    private javax.swing.JPanel pnlComandos;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosTitulo;
    private javax.swing.JPanel pnlGrafica;
    private javax.swing.JPanel pnlMatrizAdyacencia;
    private javax.swing.JTable tblMatAdy;
    // End of variables declaration//GEN-END:variables
    private void ActionSalir(final java.awt.Window inWin) {
        inWin.setVisible(false);
        inWin.dispose();

        final Window parent = inWin.getOwner();
        if (parent != null) {
            parent.setVisible(true);
        } else {
            System.exit(0);
        }
    }

    private void actionGraficar() {
        // copiar los valores de la tabla a la matriz de adyacencia
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                matAdy[i][j] = (Integer) tblMatAdy.getValueAt(i, j);
            }
        }

        // es necesario hacer un casting, para poder acceder al "setMatAdy" de PanelCanvas,
        // y pasarle asi la matriz de adyacencia, para ser dibujada en el panel
        ((PanelCanvas) pnlGrafica).setMatAdy(matAdy);
        this.repaint();

        /*
            Aqui se procede a hallar lo pares de vertices existentes
         */
        // Para etiquetar a los nodos de la matriz
        String[] etiquetaNodo = {"A", "B", "AB", "O"};

        // Crear un nuevo elemento modelo para el jlist
        DefaultListModel<String> model = new DefaultListModel<>();

        // Añadir los nuevos elementos al modelo
        model.addElement("Vértices");
        model.addElement("Adyacentes");
        model.addElement("");

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                if (matAdy[i][j] > 0) {
                    // Si hay conexion, se procede a agregar el vertice
                    model.addElement(etiquetaNodo[i] + "->" + etiquetaNodo[j]);
                }
            }
        }

        // Actualizar el jlist con el nuevo modelo
        lstVerAdy.setModel(model);
    }

}
