package vista;

import controlador.ControlAppMain;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import negocio.ArriendoCuota;
import negocio.Cliente;
import negocio.CuotaArriendo;


/**
 *
 */
public final class DlgPagarCuotasArriendo extends javax.swing.JDialog implements DlgPagarCuotasArriendo_IF {

    private ArriendoCuota arrCuo;
    private ArrayList<ArriendoCuota> list;
    private final ArrayList<JCheckBox> cbx = new ArrayList<>();


    /**
     * Creates new form DlgArriendoConCuotas
     *
     * @param parent
     */
    public DlgPagarCuotasArriendo(java.awt.Window parent) {
        super(parent, ModalityType.DOCUMENT_MODAL);
        initComponents();
        myInit();
    }


    @Override
    public void myInit() {

        final java.awt.Window me = this;

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    ControlAppMain.actionSalir(me);
                });
            }
        });

        lst_sel_cliente.addItemListener((ItemEvent event) -> {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                java.awt.EventQueue.invokeLater(() -> {
                    actionSetFchArr();
                });
            }
        });

        cbx.add(cbx1);
        cbx.add(cbx2);
        cbx.add(cbx3);
        cbx.add(cbx4);
        cbx.add(cbx5);
        cbx.add(cbx6);

        cbx.forEach((c) -> {
            c.setEnabled(false);
        });

        arrCuo = null;
        list = new ArrayList<>();

        LimpiarCampos();
        btnRealizarPago.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lst_sel_cliente = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_cuotas = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_sel_Arr = new javax.swing.JList<>();
        cbx1 = new javax.swing.JCheckBox();
        cbx2 = new javax.swing.JCheckBox();
        cbx3 = new javax.swing.JCheckBox();
        cbx4 = new javax.swing.JCheckBox();
        cbx5 = new javax.swing.JCheckBox();
        cbx6 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnRealizarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Car-Rent - Pagar Cuotas de Arriendo");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagar Cuotas de Arriendo");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setMaximumSize(new java.awt.Dimension(32000, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(82, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lst_sel_cliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lst_sel_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cliente" }));
        lst_sel_cliente.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel2.add(lst_sel_cliente, gridBagConstraints);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha Arriendo");
        jLabel2.setMaximumSize(new java.awt.Dimension(130, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(130, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));

        lst_cuotas.setMaximumSize(new java.awt.Dimension(1000, 100));
        lst_cuotas.setMinimumSize(new java.awt.Dimension(100, 100));
        lst_cuotas.setPreferredSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setViewportView(lst_cuotas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Número | Valor | ¿ Pagada ?");
        jLabel7.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PAGOS");
        jLabel8.setMaximumSize(new java.awt.Dimension(170, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(170, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel8, gridBagConstraints);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 200));

        jScrollPane2.setViewportView(lst_sel_Arr);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 5);
        jPanel3.add(jScrollPane2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel3.add(cbx1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel3.add(cbx2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel3.add(cbx3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel3.add(cbx4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel3.add(cbx5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 0, 0);
        jPanel3.add(cbx6, gridBagConstraints);

        getContentPane().add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(407, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(407, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnGuardar.setBackground(new java.awt.Color(51, 102, 0));
        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGuardar.setText("Mostrar pagos arriendo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(btnGuardar, gridBagConstraints);

        btnRealizarPago.setBackground(new java.awt.Color(51, 102, 0));
        btnRealizarPago.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRealizarPago.setText("Realizar Pago");
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(btnRealizarPago, gridBagConstraints);

        getContentPane().add(jPanel4);

        setSize(new java.awt.Dimension(810, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        actionMostrarPagosArr();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagoActionPerformed
        actionPagarCuota();
    }//GEN-LAST:event_btnRealizarPagoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPagarCuotasArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPagarCuotasArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPagarCuotasArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPagarCuotasArriendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPagarCuotasArriendo dialog = new DlgPagarCuotasArriendo(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JCheckBox cbx1;
    private javax.swing.JCheckBox cbx2;
    private javax.swing.JCheckBox cbx3;
    private javax.swing.JCheckBox cbx4;
    private javax.swing.JCheckBox cbx5;
    private javax.swing.JCheckBox cbx6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_cuotas;
    private javax.swing.JList<String> lst_sel_Arr;
    private javax.swing.JComboBox<String> lst_sel_cliente;
    // End of variables declaration//GEN-END:variables


    @Override
    public void LimpiarCampos() {
        lst_sel_cliente.setSelectedIndex(0);

        lst_sel_Arr.setModel(new DefaultListModel());
        lst_cuotas.setModel(new DefaultListModel());
    }


    @Override
    public void setVisible(boolean inB) {

        if (inB) {
            setLstCliente();
        }

        super.setVisible(inB);
    }


    public void setLstCliente() {

        lst_sel_cliente.removeAllItems();

        lst_sel_cliente.addItem("Seleccione CLIENTE");

        FrmAppMain.getCopyListC().forEach((item) -> {
            lst_sel_cliente.addItem(item.toString());
        });

        lst_sel_cliente.setSelectedIndex(0);
    }


    @Override
    public void actionSetFchArr() {
        if (lst_sel_cliente.getSelectedIndex() > 0) {

            Cliente c = FrmAppMain.getCopyListC().get(lst_sel_cliente.getSelectedIndex() - 1);

            list.clear();

            DefaultListModel model = (DefaultListModel) lst_sel_Arr.getModel();
            model.removeAllElements();

            FrmAppMain.getListArr().forEach((item) -> {
                if (item.getCliente().getId() == c.getId()) {
                    list.add(item);
                    model.addElement(item.getFecArr());
                }
            });

        }
    }


    @Override
    public void actionMostrarPagosArr() {

        if (lst_sel_Arr.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fecha de arriendo");
            lst_sel_Arr.requestFocus();
            return;
        }

        DefaultListModel model = (DefaultListModel) lst_cuotas.getModel();
        model.removeAllElements();

        arrCuo = list.get(lst_sel_Arr.getSelectedIndex());

        int idx = 0;
        for (CuotaArriendo item : arrCuo.getListCuo()) {

            model.addElement(item.toString());

            cbx.get(idx).setSelected(item.getPagada());
            cbx.get(idx).setEnabled(!item.getPagada());

            idx++;
        }

        for (int i = idx; i < 6; i++) {
            cbx.get(i).setEnabled(false);
        }

        btnRealizarPago.setEnabled(true);
        btnGuardar.setEnabled(false);

        lst_sel_cliente.setEnabled(false);

        lst_sel_Arr.setEnabled(false);
        lst_cuotas.setEnabled(true);

    }


    @Override
    public void actionPagarCuota() {

        DefaultListModel model = (DefaultListModel) lst_cuotas.getModel();
        model.removeAllElements();

        arrCuo = list.get(lst_sel_Arr.getSelectedIndex());

        int cont = 0;
        int idx = 0;
        for (CuotaArriendo item : arrCuo.getListCuo()) {

            if (cbx.get(idx).isSelected() && cbx.get(idx).isEnabled()) {
                cbx.get(idx).setEnabled(false);
                cont++;
                item.PagarCuota(true);
            }

            idx++;
        }

        if (cont > 0) {
            JOptionPane.showMessageDialog(this, "Cuota pagada con exito");
            FrmAppMain.WriteArrCuo();
            controlador.ControlAppMain.actionSalir(this);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una cuota");
        }

    }
}
