package vista;

import controlador.ControlAppMain;
import java.util.ArrayList;
import negocio.ArriendoCuota;
import negocio.Cliente;
import negocio.Vehiculo;


/**
 *
 */
public final class FrmAppMain extends javax.swing.JFrame implements FrmAppMain_IF {

    private static final ArrayList<Cliente> listC = new ArrayList<Cliente>();
    private static final ArrayList<Vehiculo> listV = new ArrayList<Vehiculo>();
    private static final ArrayList<ArriendoCuota> listArr = new ArrayList<ArriendoCuota>();


    static ArrayList<String> getListStrFch(Cliente inC) {
        ArrayList<String> aux = new ArrayList<>();

        for (ArriendoCuota item : listArr) {
            if (inC.getId() == item.getCliente().getId()) {
                aux.add(item.getFecArr());
            }
        }

        return aux;
    }


    /**
     * Creates new form FrmAppMain
     */
    public FrmAppMain() {
        initComponents();
        myInit();
    }


    @Override
    public void myInit() {

        final java.awt.Window me = this;

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    ControlAppMain.actionSalir(me);
                });
            }
        });

        Cliente.ReadFromFile(listC);
        Vehiculo.ReadFromFile(listV);
        ArriendoCuota.ReadFromFile(listArr);
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuArrCuotas = new javax.swing.JMenuItem();
        mnuPagarCuotaArr = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenuItem();
        mnuVehiculo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenu1.add(jSeparator1);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mnuSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenu2.add(jSeparator2);

        mnuArrCuotas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuArrCuotas.setText("Arriendo con Cuotas");
        mnuArrCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArrCuotasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuArrCuotas);

        mnuPagarCuotaArr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuPagarCuotaArr.setText("Pagar Cuotas Arriendos");
        mnuPagarCuotaArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagarCuotaArrActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPagarCuotaArr);

        mnuCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuCliente.setText("Agregar Cliente");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCliente);

        mnuVehiculo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuVehiculo.setText("Agregar Vehículo");
        mnuVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuVehiculo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArrCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArrCuotasActionPerformed
        ControlAppMain.actionDlgArriendoConCuotas(this);
    }//GEN-LAST:event_mnuArrCuotasActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        ControlAppMain.actionSalir(this);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuPagarCuotaArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagarCuotaArrActionPerformed
        ControlAppMain.actionDlgPagarCuotasArriendo(this);
    }//GEN-LAST:event_mnuPagarCuotaArrActionPerformed

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        ControlAppMain.actionDlgCliente(this);
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void mnuVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculoActionPerformed
        ControlAppMain.actionDlgVehiculo(this);
    }//GEN-LAST:event_mnuVehiculoActionPerformed


    public static ArrayList<Cliente> getCopyListC() {
        return Cliente.getCopyList(listC);
    }


    public static ArrayList<Vehiculo> getCopyListV() {
        return Vehiculo.getCopyListV(listV);
    }


    public static ArrayList<ArriendoCuota> getListArr() {
        return listArr;
    }


    public static boolean WriteVehiculo() {
        return Vehiculo.WriteToFile(listV);
    }


    public static boolean addCliente(Cliente inCliente) {

        listC.add(inCliente);

        return Cliente.WriteToFile(listC);
    }


    public static boolean addVehiculo(Vehiculo inVehiculo) {

        listV.add(inVehiculo);

        return Vehiculo.WriteToFile(listV);
    }


    public static boolean addArriendoCuota(ArriendoCuota inArrCuo) {

        listArr.add(inArrCuo);

        return ArriendoCuota.WriteToFile(listArr);
    }


    public static boolean WriteArrCuo() {

        return ArriendoCuota.WriteToFile(listArr);
    }


    public static Cliente getCliente(int idx) {

        return listC.get(idx);
    }


    public static Cliente getCliente(String InStrItem) {

        for (Cliente item : listC) {
            if (item.toString().equals(InStrItem)) {
                return item;
            }
        }

        return null;
    }


    public static Vehiculo getVehiculo(int idx) {

        return listV.get(idx);
    }


    public static Vehiculo getVehiculo(String inStrItem) {

        for (Vehiculo item : listV) {
            if (item.toString().equals(inStrItem)) {
                return item;
            }
        }

        return null;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmAppMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuArrCuotas;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuPagarCuotaArr;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVehiculo;
    // End of variables declaration//GEN-END:variables
}
