package com.app;

import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;


/**
 *
 */
public class DlgPagoIVA extends javax.swing.JDialog {

    private final List<Producto> listVenta;


    /**
     * Creates new form DlgVenta
     *
     * @param parent
     * @param inListVenta
     */
    public DlgPagoIVA(java.awt.Window parent, List<Producto> inListVenta) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        listVenta = inListVenta;
        myInitComponents();
    }


    private void myInitComponents() {

        final java.awt.Window me = this;

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    actionSalir(me);
                });
            }
        });

        ActComp();

    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_prod = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel17 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel19 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel18 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnPagar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Supermercado - Pagar con IVA");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Producto");
        jLabel15.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel15, gridBagConstraints);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Precio");
        jLabel16.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel16, gridBagConstraints);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cantidad");
        jLabel14.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel14, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(250, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 300));

        jScrollPane1.setViewportView(lst_prod);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 65534));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel3.add(filler2);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("I.V.A.");
        jLabel17.setAlignmentX(0.5F);
        jPanel3.add(jLabel17);

        txtIVA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIVA.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        txtIVA.setMinimumSize(new java.awt.Dimension(4, 25));
        txtIVA.setPreferredSize(new java.awt.Dimension(71, 25));
        jPanel3.add(txtIVA);
        jPanel3.add(filler3);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Sub-Total");
        jLabel19.setAlignmentX(0.5F);
        jPanel3.add(jLabel19);

        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubTotal.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        txtSubTotal.setMinimumSize(new java.awt.Dimension(4, 25));
        txtSubTotal.setPreferredSize(new java.awt.Dimension(71, 25));
        jPanel3.add(txtSubTotal);
        jPanel3.add(filler8);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Total");
        jLabel20.setAlignmentX(0.5F);
        jPanel3.add(jLabel20);

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        txtTotal.setMinimumSize(new java.awt.Dimension(4, 25));
        txtTotal.setPreferredSize(new java.awt.Dimension(71, 25));
        jPanel3.add(txtTotal);

        jPanel2.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 200));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel4.add(filler5);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Pagar Compra");
        jLabel18.setAlignmentX(0.5F);
        jPanel4.add(jLabel18);
        jPanel4.add(filler6);
        jPanel4.add(filler7);

        btnPagar.setText("Pagar");
        btnPagar.setAlignmentX(0.5F);
        btnPagar.setMaximumSize(new java.awt.Dimension(90, 25));
        btnPagar.setMinimumSize(new java.awt.Dimension(90, 25));
        btnPagar.setPreferredSize(new java.awt.Dimension(90, 25));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel4.add(btnPagar);
        jPanel4.add(filler1);

        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.setMaximumSize(new java.awt.Dimension(90, 25));
        btnCancelar.setMinimumSize(new java.awt.Dimension(90, 25));
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        setSize(new java.awt.Dimension(610, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        actionSalir(this);
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        actionSalir(this);
    }//GEN-LAST:event_btnCancelarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPagoIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPagoIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPagoIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPagoIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPagoIVA dialog = new DlgPagoIVA(new javax.swing.JFrame(), new ArrayList<Producto>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_prod;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables


    public static boolean actionSalir(Window win) {

        win.setVisible(false);
        win.dispose();

        final Window parent = win.getOwner();
        if (parent != null) {
            parent.setVisible(true);
        } else {
            System.exit(0);
        }

        return true;
    }


    private void ClearComp() {

        txtIVA.setText("");
        txtSubTotal.setText("");
        txtTotal.setText("");

        if (listVenta.size() <= 0) {
            btnPagar.setEnabled(false);
        }

        lst_prod.setModel(new DefaultListModel());

    }


    private void ActComp() {

        ClearComp();

        DefaultListModel model = (DefaultListModel) lst_prod.getModel();
        model.removeAllElements();

        int subTotal = 0;
        for (Producto item : listVenta) {
            model.addElement(item.toString());
            subTotal += item.getPrecio() * item.getCantidad();
        }

        txtIVA.setText(String.valueOf(subTotal * 0.19));
        txtSubTotal.setText(String.valueOf(subTotal));
        txtTotal.setText(String.valueOf(subTotal * 1.19));
    }

}
