package com.app;

import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 */
public class DlgVenta extends javax.swing.JDialog {

    private List<Producto> listProd = FrmAppMain.GetListProd();
    private List<Producto> listVenta;

    private List<JCheckBox> listCheckBox;
    private List<JLabel> listLabel;
    private List<JTextField> listText;


    /**
     * Creates new form DlgVenta
     *
     * @param parent
     */
    public DlgVenta(java.awt.Frame parent) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        myInitComponents();
    }


    private void myInitComponents() {

        final java.awt.Window me = this;

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    actionSalir(me);
                });
            }
        });

        listCheckBox = new ArrayList<>();
        listCheckBox.add(jCheckBox1);
        listCheckBox.add(jCheckBox2);
        listCheckBox.add(jCheckBox3);
        listCheckBox.add(jCheckBox4);
        listCheckBox.add(jCheckBox5);
        listCheckBox.add(jCheckBox6);
        listCheckBox.add(jCheckBox7);
        listCheckBox.add(jCheckBox8);
        listCheckBox.add(jCheckBox9);
        listCheckBox.add(jCheckBox10);
        listCheckBox.add(jCheckBox11);
        listCheckBox.add(jCheckBox12);
        listCheckBox.add(jCheckBox13);

        listLabel = new ArrayList<>();
        listLabel.add(jLabel1);
        listLabel.add(jLabel2);
        listLabel.add(jLabel3);
        listLabel.add(jLabel4);
        listLabel.add(jLabel5);
        listLabel.add(jLabel6);
        listLabel.add(jLabel7);
        listLabel.add(jLabel8);
        listLabel.add(jLabel9);
        listLabel.add(jLabel10);
        listLabel.add(jLabel11);
        listLabel.add(jLabel12);
        listLabel.add(jLabel13);

        listText = new ArrayList<>();
        listText.add(jTextField1);
        listText.add(jTextField2);
        listText.add(jTextField3);
        listText.add(jTextField4);
        listText.add(jTextField5);
        listText.add(jTextField6);
        listText.add(jTextField7);
        listText.add(jTextField8);
        listText.add(jTextField9);
        listText.add(jTextField10);
        listText.add(jTextField11);
        listText.add(jTextField12);
        listText.add(jTextField13);

        ActComp();

    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel17 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        txtProducto = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnAgregar = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel18 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        rdBoleta = new javax.swing.JRadioButton();
        rdFactura = new javax.swing.JRadioButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Supermercado - Venta");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jCheckBox1.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox2.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox2, gridBagConstraints);

        jCheckBox3.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox3.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox3.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox3, gridBagConstraints);

        jCheckBox4.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox4.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox4.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox4, gridBagConstraints);

        jCheckBox5.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox5.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox5.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox5, gridBagConstraints);

        jCheckBox6.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox6.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox6.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox6, gridBagConstraints);

        jCheckBox7.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox7.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox7.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox7, gridBagConstraints);

        jCheckBox8.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox8.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox8.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox8, gridBagConstraints);

        jCheckBox9.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox9.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox9.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox9, gridBagConstraints);

        jCheckBox10.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox10.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox10.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox10, gridBagConstraints);

        jCheckBox11.setEnabled(false);
        jCheckBox11.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox11.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox11.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox11, gridBagConstraints);

        jCheckBox12.setEnabled(false);
        jCheckBox12.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox12.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox12.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox12, gridBagConstraints);

        jCheckBox13.setEnabled(false);
        jCheckBox13.setMaximumSize(new java.awt.Dimension(120, 25));
        jCheckBox13.setMinimumSize(new java.awt.Dimension(120, 25));
        jCheckBox13.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jCheckBox13, gridBagConstraints);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jTextField1, gridBagConstraints);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField2.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField2, gridBagConstraints);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField3.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField3.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField3, gridBagConstraints);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField4.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField4.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField4, gridBagConstraints);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField5.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField5.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField5, gridBagConstraints);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField6.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField6.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField6, gridBagConstraints);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField7.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField7.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField7, gridBagConstraints);

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField8.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField8.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField8, gridBagConstraints);

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField9.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField9.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField9, gridBagConstraints);

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField10.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField10.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField10, gridBagConstraints);

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setEnabled(false);
        jTextField11.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField11.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField11.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField11, gridBagConstraints);

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setEnabled(false);
        jTextField12.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField12.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField12.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField12, gridBagConstraints);

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField13.setEnabled(false);
        jTextField13.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField13.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField13.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jTextField13, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(75, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel13, gridBagConstraints);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel15, gridBagConstraints);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel16, gridBagConstraints);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel14, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 65534));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel3.add(filler2);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Producto Nuevo");
        jLabel17.setAlignmentX(0.5F);
        jPanel3.add(jLabel17);
        jPanel3.add(filler1);

        txtProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProducto.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        txtProducto.setMinimumSize(new java.awt.Dimension(4, 25));
        txtProducto.setPreferredSize(new java.awt.Dimension(71, 25));
        jPanel3.add(txtProducto);
        jPanel3.add(filler3);

        btnAgregar.setText("Agregar");
        btnAgregar.setAlignmentX(0.5F);
        btnAgregar.setMaximumSize(new java.awt.Dimension(80, 25));
        btnAgregar.setMinimumSize(new java.awt.Dimension(80, 25));
        btnAgregar.setPreferredSize(new java.awt.Dimension(80, 25));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar);
        jPanel3.add(filler4);

        jPanel2.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 200));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel4.add(filler5);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Pagar Compra");
        jLabel18.setAlignmentX(0.5F);
        jPanel4.add(jLabel18);
        jPanel4.add(filler6);

        buttonGroup1.add(rdBoleta);
        rdBoleta.setSelected(true);
        rdBoleta.setText("Boleta");
        rdBoleta.setAlignmentX(0.5F);
        jPanel4.add(rdBoleta);

        buttonGroup1.add(rdFactura);
        rdFactura.setText("Factura");
        rdFactura.setAlignmentX(0.5F);
        jPanel4.add(rdFactura);
        jPanel4.add(filler7);

        btnPagar.setText("Pagar");
        btnPagar.setAlignmentX(0.5F);
        btnPagar.setMaximumSize(new java.awt.Dimension(80, 25));
        btnPagar.setMinimumSize(new java.awt.Dimension(80, 25));
        btnPagar.setPreferredSize(new java.awt.Dimension(80, 25));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel4.add(btnPagar);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        setSize(new java.awt.Dimension(610, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        actionAgregarProd();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        actionPagar();
    }//GEN-LAST:event_btnPagarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgVenta dialog = new DlgVenta(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton rdBoleta;
    private javax.swing.JRadioButton rdFactura;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables


    public static boolean actionSalir(Window win) {

        win.setVisible(false);
        win.dispose();

        final Window parent = win.getOwner();
        if (parent != null) {
            parent.setVisible(true);
        } else {
            System.exit(0);
        }

        return true;
    }


    private void ClearComp() {

        listCheckBox.forEach((item) -> {
            item.setEnabled(false);
            item.setSelected(false);
        });

        listLabel.forEach((item) -> {
            item.setEnabled(false);
            item.setText("");
        });

        listText.forEach((item) -> {
            item.setEnabled(false);
            item.setText("");
        });

        txtProducto.setText("");

        if (listProd.size() < 13) {
            txtProducto.setEnabled(true);
            btnAgregar.setEnabled(true);
        } else {
            txtProducto.setEnabled(false);
            btnAgregar.setEnabled(false);
        }

    }


    private void actionAgregarProd() {

        String nombreProd = txtProducto.getText().trim();
        if (nombreProd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre invalido");
            txtProducto.requestFocus();
            return;
        }

        boolean encontrado = false;
        for (Producto item : listProd) {
            if (item.getNombre().equalsIgnoreCase(nombreProd)) {
                encontrado = true;
                break;
            }
        }

        if (encontrado) {
            JOptionPane.showMessageDialog(this, "Nombre invalido, ya existe");
            txtProducto.requestFocus();
            return;
        }

        int precioProd = (int) (500 + 1500 * Math.random()); // nuemro entre 500 y 2000

        listProd.add(new Producto(nombreProd, precioProd));

        Producto.WriteToFile(listProd);

        ActComp();

    }


    private void ActComp() {

        ClearComp();

        listProd = FrmAppMain.GetListProd();
        int cont = 0;
        for (Producto item : listProd) {
            listCheckBox.get(cont).setEnabled(true);
            listCheckBox.get(cont).setText(item.getNombre());

            listLabel.get(cont).setEnabled(true);
            listLabel.get(cont).setText(String.valueOf(item.getPrecio()));

            listText.get(cont).setEnabled(true);

            cont++;
        }
    }


    private void actionPagar() {

        listVenta = new ArrayList<>();

        // Validar entradas
        for (int i = 0; i < listProd.size(); i++) {

            if (listCheckBox.get(i).isSelected()) {

                String strCant = listText.get(i).getText().trim();
                int cant;

                try {
                    cant = Integer.parseInt(strCant);
                } catch (NumberFormatException inNumberFormatException) {
                    JOptionPane.showMessageDialog(this, "Cantidad invalida");
                    listText.get(i).requestFocus();
                    return;
                }

                if (cant <= 0) {
                    JOptionPane.showMessageDialog(this, "Cantidad invalida");
                    listText.get(i).requestFocus();
                    return;
                }

                listVenta.add(new Producto(listProd.get(i).getNombre(), listProd.get(i).getPrecio(), cant));
            }

        }

        if (listVenta.size() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un producto");
            listText.get(0).requestFocus();
            return;
        }

        if (rdBoleta.isSelected()) {
            final Window me = this;
            java.awt.EventQueue.invokeLater(() -> {
                new DlgPagoBoleta(me, listVenta).setVisible(true);
                ActComp();
            });

        } else if (rdFactura.isSelected()) {
            final Window me = this;
            java.awt.EventQueue.invokeLater(() -> {
                new DlgPagoIVA(me, listVenta).setVisible(true);
                ActComp();
            });
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un metodo de pago");
            rdBoleta.requestFocus();
        }

    }

}
