/*
 * Todos los derechos reservados por CAPIP Sistemas C.A., Venezuela
 * RIF J-407111787
 * capipsistemas@gmail.com, baba.orere@gmail.com
 * @2016, 2017, 2018
 */
package configuracion;

import capipsistema.CapipPropiedades;
import capipsistema.Conn;
import capipsistema.UserTrack;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import utils.PnlImagenFondo;

/**
 *
 * @author Capip Sistemas C.A.
 */
public class DlgFirmaRpt extends javax.swing.JDialog {

    private final java.awt.Window parent;

    private boolean isGuardar;

    /**
     * Creates new form DlgIvaPorcAplic
     *
     * @param _parent
     */
    public DlgFirmaRpt(java.awt.Window _parent) {
        super(_parent, ModalityType.APPLICATION_MODAL);
        initComponents();

        parent = _parent;

        setOwnBehavior();
        setCompBehavior();
        setStartConditions();
    }

    /**
     * Rev 04/10/2016
     */
    private void setOwnBehavior() {
        try {
            UserTrack.trackUser(getClass().getName(), "INIT", getTitle());
        } catch (final Exception _ex) {
            JOptionPane.showMessageDialog(null, _ex);
        }

        setTitle(CapipPropiedades.CAPIP_SISTEMAS + " - " + getTitle() + " - " + CapipPropiedades.CAPIP_CLIENTE_RAZONSOCIAL);

        // Establecer la acción al cerrar ventana
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                actSalir();
            }
        });

        // Para salir con la tecla ESC
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");

        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                actSalir();
            }
        });
    }

    /**
     * Rev 04/10/2016
     */
    private void setCompBehavior() {

    }

    /**
     * Rev 02/10/2016
     */
    private void setStartConditions() {
        isGuardar = false;
        actUpdate();
    }

    /**
     * Para Reubicar la ventana al ser visualizada Rev 25/09/2016
     *
     * @param _b
     */
    @Override
    public void setVisible(boolean _b) {
        // Para mostrar la ventana en el tope de la pantalla
        if (_b) {
            setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) / 2, 10);
        }

        super.setVisible(_b);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlImagenFondo = new PnlImagenFondo();
        pnlComponentes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDesc_1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFunc_1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDesc_2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFunc_2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDesc_3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFunc_3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDesc_4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFunc_4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDesc_5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFunc_5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesc_6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFunc_6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDesc_7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFunc_7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDesc_8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFunc_8 = new javax.swing.JTextField();
        pnlComandos = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración Firmas en Reportes");

        pnlImagenFondo.setLayout(new javax.swing.BoxLayout(pnlImagenFondo, javax.swing.BoxLayout.PAGE_AXIS));

        pnlComponentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlComponentes.setMaximumSize(new java.awt.Dimension(800, 620));
        pnlComponentes.setMinimumSize(new java.awt.Dimension(800, 620));
        pnlComponentes.setOpaque(false);
        pnlComponentes.setPreferredSize(new java.awt.Dimension(800, 620));
        pnlComponentes.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Desc. Firma 1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel1, gridBagConstraints);

        txtDesc_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_1.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_1.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_1.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_1.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_1, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Func. Firma 1");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel10, gridBagConstraints);

        txtFunc_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_1.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_1.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_1.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_1, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Desc. Firma 2");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel11.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel11, gridBagConstraints);

        txtDesc_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_2.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_2.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_2.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_2.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_2, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Func. Firma 2");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel12.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel12.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel12.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel12, gridBagConstraints);

        txtFunc_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_2.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_2.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_2.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_2, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Desc. Firma 3");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel13.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel13.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel13.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel13, gridBagConstraints);

        txtDesc_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_3.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_3.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_3.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_3.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_3, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Func. Firma 3");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel8, gridBagConstraints);

        txtFunc_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_3.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_3.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_3.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_3, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Desc. Firma 4");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel15.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel15.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel15.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel15, gridBagConstraints);

        txtDesc_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_4.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_4.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_4.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_4.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_4, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Func. Firma 4");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel6, gridBagConstraints);

        txtFunc_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_4.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_4.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_4.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_4, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Desc. Firma 5");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel9, gridBagConstraints);

        txtDesc_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_5.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_5.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_5.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_5.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Func. Firma 5");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel7, gridBagConstraints);

        txtFunc_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_5.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_5.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_5.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_5, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Desc. Firma 6");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel3, gridBagConstraints);

        txtDesc_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_6.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_6.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_6.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_6.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_6, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Func. Firma 6");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel2, gridBagConstraints);

        txtFunc_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_6.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_6.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_6.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_6, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Desc. Firma 7");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel4, gridBagConstraints);

        txtDesc_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_7.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_7.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_7.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_7.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_7, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Func. Firma 7");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel5, gridBagConstraints);

        txtFunc_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_7.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_7.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_7.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_7, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Desc. Firma 8");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel14.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel14.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlComponentes.add(jLabel14, gridBagConstraints);

        txtDesc_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesc_8.setDisabledTextColor(new java.awt.Color(112, 0, 0));
        txtDesc_8.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDesc_8.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDesc_8.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlComponentes.add(txtDesc_8, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Func. Firma 8");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel16.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel16.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlComponentes.add(jLabel16, gridBagConstraints);
        jLabel16.getAccessibleContext().setAccessibleName("Funcionario Firma 8");

        txtFunc_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFunc_8.setMaximumSize(new java.awt.Dimension(250, 30));
        txtFunc_8.setMinimumSize(new java.awt.Dimension(250, 30));
        txtFunc_8.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlComponentes.add(txtFunc_8, gridBagConstraints);

        pnlImagenFondo.add(pnlComponentes);

        pnlComandos.setOpaque(false);
        pnlComandos.setLayout(new java.awt.GridBagLayout());

        btnSave.setBackground(new java.awt.Color(153, 153, 0));
        btnSave.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSaveFocusLost(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlComandos.add(btnSave, gridBagConstraints);

        btnCancel.setBackground(new java.awt.Color(153, 153, 0));
        btnCancel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCancel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCancelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelFocusLost(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        pnlComandos.add(btnCancel, gridBagConstraints);

        btnRecargar.setBackground(new java.awt.Color(153, 153, 0));
        btnRecargar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRecargar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRecargarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnRecargarFocusLost(evt);
            }
        });
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlComandos.add(btnRecargar, gridBagConstraints);

        pnlImagenFondo.add(pnlComandos);

        getContentPane().add(pnlImagenFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        actSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        actSalir();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusGained
        getRootPane().setDefaultButton(btnSave);
    }//GEN-LAST:event_btnSaveFocusGained

    private void btnSaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusLost
        getRootPane().setDefaultButton(null);
    }//GEN-LAST:event_btnSaveFocusLost

    private void btnCancelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelFocusGained
        getRootPane().setDefaultButton(btnCancel);
    }//GEN-LAST:event_btnCancelFocusGained

    private void btnCancelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelFocusLost
        getRootPane().setDefaultButton(null);
    }//GEN-LAST:event_btnCancelFocusLost

    private void btnRecargarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRecargarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargarFocusGained

    private void btnRecargarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRecargarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargarFocusLost

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        actUpdate();
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * Rev 25/12/2016
     *
     */
    private void actClear() {
        txtDesc_1.setText("");
        txtDesc_2.setText("");
        txtDesc_3.setText("");
        txtDesc_4.setText("");

        txtFunc_1.setText("");
        txtFunc_2.setText("");
        txtFunc_3.setText("");
        txtFunc_4.setText("");

        txtDesc_5.setText("");
        txtDesc_6.setText("");
        txtDesc_7.setText("");
        txtDesc_8.setText("");

        txtFunc_5.setText("");
        txtFunc_6.setText("");
        txtFunc_7.setText("");
        txtFunc_8.setText("");
    }

    /**
     * Rev 25/12/2016
     *
     */
    private void actUpdate() {
        actClear();
        try {

            ResultSet rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_1'");
            if (rs.next()) {
                txtDesc_1.setText(rs.getString("valor"));
            } else {
                txtDesc_1.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_2'");
            if (rs.next()) {
                txtDesc_2.setText(rs.getString("valor"));
            } else {
                txtDesc_2.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_3'");
            if (rs.next()) {
                txtDesc_3.setText(rs.getString("valor"));
            } else {
                txtDesc_3.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_4'");
            if (rs.next()) {
                txtDesc_4.setText(rs.getString("valor"));
            } else {
                txtDesc_4.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_5'");
            if (rs.next()) {
                txtDesc_5.setText(rs.getString("valor"));
            } else {
                txtDesc_5.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_6'");
            if (rs.next()) {
                txtDesc_6.setText(rs.getString("valor"));
            } else {
                txtDesc_6.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_7'");
            if (rs.next()) {
                txtDesc_7.setText(rs.getString("valor"));
            } else {
                txtDesc_7.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'DESC_8'");
            if (rs.next()) {
                txtDesc_8.setText(rs.getString("valor"));
            } else {
                txtDesc_8.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            ////////////////////////////////////////////////////////////////////////////////////////////////
            //
            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_1'");
            if (rs.next()) {
                txtFunc_1.setText(rs.getString("valor"));
            } else {
                txtFunc_1.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_2'");
            if (rs.next()) {
                txtFunc_2.setText(rs.getString("valor"));
            } else {
                txtFunc_2.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_3'");
            if (rs.next()) {
                txtFunc_3.setText(rs.getString("valor"));
            } else {
                txtFunc_3.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_4'");
            if (rs.next()) {
                txtFunc_4.setText(rs.getString("valor"));
            } else {
                txtFunc_4.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_5'");
            if (rs.next()) {
                txtFunc_5.setText(rs.getString("valor"));
            } else {
                txtFunc_5.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_6'");
            if (rs.next()) {
                txtFunc_6.setText(rs.getString("valor"));
            } else {
                txtFunc_6.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_7'");
            if (rs.next()) {
                txtFunc_7.setText(rs.getString("valor"));
            } else {
                txtFunc_7.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

            rs = Conn.executeQuery("SELECT * FROM global WHERE nombre= 'FUNC_8'");
            if (rs.next()) {
                txtFunc_8.setText(rs.getString("valor"));
            } else {
                txtFunc_8.setText("");
                throw new Exception("Valor no encontrado");
            }
            rs.close();

        } catch (final Exception _ex) {
            JOptionPane.showMessageDialog(this, "Error al tratar de leer la Base de Datos" + System.getProperty("line.separator") + _ex);
        }
    }

    /**
     * Rev 25/12/2016
     *
     */
    private void actSave() {

        final String desc[] = new String[8];

        desc[0] = txtDesc_1.getText().trim().toUpperCase();
        desc[1] = txtDesc_2.getText().trim().toUpperCase();
        desc[2] = txtDesc_3.getText().trim().toUpperCase();
        desc[3] = txtDesc_4.getText().trim().toUpperCase();
        desc[4] = txtDesc_5.getText().trim().toUpperCase();
        desc[5] = txtDesc_6.getText().trim().toUpperCase();
        desc[6] = txtDesc_7.getText().trim().toUpperCase();
        desc[7] = txtDesc_8.getText().trim().toUpperCase();

        final String func[] = new String[8];
        func[0] = txtFunc_1.getText().trim().toUpperCase();
        func[1] = txtFunc_2.getText().trim().toUpperCase();
        func[2] = txtFunc_3.getText().trim().toUpperCase();
        func[3] = txtFunc_4.getText().trim().toUpperCase();
        func[4] = txtFunc_5.getText().trim().toUpperCase();
        func[5] = txtFunc_6.getText().trim().toUpperCase();
        func[6] = txtFunc_7.getText().trim().toUpperCase();
        func[7] = txtFunc_8.getText().trim().toUpperCase();

        try {
            for (int i = 0; i < 8; i++) {
                int y;
                try (PreparedStatement pst = Conn.getConnection().prepareStatement("UPDATE global SET valor= ? WHERE nombre= ?")) {
                    pst.setString(1, desc[i]);
                    pst.setString(2, "DESC_" + (i + 1));
                    if (pst.executeUpdate() != 1) {
                        throw new Exception("Registro no actualizado");
                    }
                }
            }

            ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            //
            //
            for (int i = 0; i < 8; i++) {
                try (PreparedStatement pst = Conn.getConnection().prepareStatement("UPDATE global SET valor= ? WHERE nombre= ?")) {
                    pst.setString(1, func[i]);
                    pst.setString(2, "FUNC_" + (i + 1));
                    if (pst.executeUpdate() != 1) {
                        throw new Exception("Registro no actualizado");
                    }
                }
            }

        } catch (final Exception _ex) {
            JOptionPane.showMessageDialog(this, "Error al tratar de guardar el registro" + System.getProperty("line.separator") + _ex);
        }

        actUpdate();
        isGuardar = true;
    }

    /**
     * Rev 03/10/2016
     */
    private void actSalir() {

        if (isGuardar) {
            JOptionPane.showMessageDialog(this, "Se ha realizar una operación de actualizacion en la Base de Datos" + System.getProperty("line.separator")
                + "Se procedera a cerrar el Programa, para que los cambios se hagan efectivos");
            System.exit(0);
        }

        if (parent != null) {
            final java.awt.Window me = this;
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    parent.setVisible(true);
                    me.dispose();
                }
            });

        } else {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgFirmaRpt dialog = new DlgFirmaRpt(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlComandos;
    private javax.swing.JPanel pnlComponentes;
    private javax.swing.JPanel pnlImagenFondo;
    private javax.swing.JTextField txtDesc_1;
    private javax.swing.JTextField txtDesc_2;
    private javax.swing.JTextField txtDesc_3;
    private javax.swing.JTextField txtDesc_4;
    private javax.swing.JTextField txtDesc_5;
    private javax.swing.JTextField txtDesc_6;
    private javax.swing.JTextField txtDesc_7;
    private javax.swing.JTextField txtDesc_8;
    private javax.swing.JTextField txtFunc_1;
    private javax.swing.JTextField txtFunc_2;
    private javax.swing.JTextField txtFunc_3;
    private javax.swing.JTextField txtFunc_4;
    private javax.swing.JTextField txtFunc_5;
    private javax.swing.JTextField txtFunc_6;
    private javax.swing.JTextField txtFunc_7;
    private javax.swing.JTextField txtFunc_8;
    // End of variables declaration//GEN-END:variables

}
