package com.app.controlanimal;

import java.awt.Window;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 */
public class DlgControlVentas extends javax.swing.JDialog {

    private List<Animal> listAlta;
    private List<Animal> listBaja;


    /**
     * Creates new form DlgControlVentas
     *
     * @param parent
     */
    public DlgControlVentas(java.awt.Window parent) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        myInit();
    }


    private void myInit() {

        final java.awt.Window me = this;

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    actionSalir(me);
                });
            }
        });

        listAlta = FrmAppMain.getListAlta();
        listBaja = FrmAppMain.getListBaja();

        txtCantVentas.setText(String.valueOf(listBaja.size()));

        float sumaVentas = 0;
        float sumaGanancias = 0;
        for (int i = 0; i < listBaja.size(); i++) {
            Animal animal = listBaja.get(i);
            sumaVentas += animal.getPrecioVenta();
            sumaGanancias = animal.getPrecioVenta() - animal.getPrecioCompra();
        }

        txtMontoVentas.setText(String.valueOf(sumaVentas));
        txtGanancias.setText(String.valueOf(sumaGanancias));

        if (sumaVentas > 100000) {
            JOptionPane.showMessageDialog(this, "El dia finalizo con exito");
        } else {
            JOptionPane.showMessageDialog(this, "Ponerte al dia con las ventas");
        }

    }


    public static boolean actionSalir(Window inWin) {

        Window parent = inWin.getOwner();

        if (parent != null) {
            inWin.setVisible(false);
            inWin.dispose();
            parent.setVisible(true);
        } else {
            System.exit(0);
        }

        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCantVentas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMontoVentas = new javax.swing.JTextField();
        txtGanancias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Control de Ventas");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ventas Realizadas");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 52, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        txtCantVentas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCantVentas.setMaximumSize(new java.awt.Dimension(80, 30));
        txtCantVentas.setMinimumSize(new java.awt.Dimension(80, 30));
        txtCantVentas.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 0, 100);
        jPanel2.add(txtCantVentas, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad de Ventas");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 52, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Monto de las Ventas");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 52, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Ganancias");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 52, 60, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        txtMontoVentas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMontoVentas.setMaximumSize(new java.awt.Dimension(80, 30));
        txtMontoVentas.setMinimumSize(new java.awt.Dimension(80, 30));
        txtMontoVentas.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 100);
        jPanel2.add(txtMontoVentas, gridBagConstraints);

        txtGanancias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtGanancias.setMaximumSize(new java.awt.Dimension(80, 30));
        txtGanancias.setMinimumSize(new java.awt.Dimension(80, 30));
        txtGanancias.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 60, 100);
        jPanel2.add(txtGanancias, gridBagConstraints);

        getContentPane().add(jPanel2);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantVentas;
    private javax.swing.JTextField txtGanancias;
    private javax.swing.JTextField txtMontoVentas;
    // End of variables declaration//GEN-END:variables
}
