package com.app.controlanimal;

import java.awt.Window;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */
public class FrmAppMain extends javax.swing.JFrame {

    private static final ArrayList<Animal> listAlta = new ArrayList<>();
    private static final ArrayList<Animal> listBaja = new ArrayList<>();


    /**
     * Creates new form FrmAppMain
     */
    public FrmAppMain() {
        initComponents();
        myInit();
    }


    private void myInit() {

        final java.awt.Window me = this;

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                java.awt.EventQueue.invokeLater(() -> {
                    actionSalir(me);
                });
            }
        });

        // Agregar 30 animales
        for (int i = 0; i < 30; i++) {
            String raza = "raza " + ((i % 3) + 1);
            String ubicacion = "lote " + ((i % 3) + 1);
            float pCompra = 100;
            float pVenta = 200;
            listAlta.add(new Animal(raza, ubicacion, pCompra, pVenta));
        }
    }


    public static List<Animal> getListAlta() {
        return listAlta;
    }


    public static List<Animal> getListBaja() {
        return listBaja;
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuVenderAnimal = new javax.swing.JMenuItem();
        mnuResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Control Animal");

        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenu2.setText("Archivo");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenu2.add(jSeparator1);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mnuSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");
        jMenu3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenu3.add(jSeparator2);

        mnuVenderAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuVenderAnimal.setText("Vender Animal");
        mnuVenderAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenderAnimalActionPerformed(evt);
            }
        });
        jMenu3.add(mnuVenderAnimal);

        mnuResumen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuResumen.setText("Resumen Ventas Diarias");
        mnuResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuResumenActionPerformed(evt);
            }
        });
        jMenu3.add(mnuResumen);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(810, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        actionSalir(this);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuVenderAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenderAnimalActionPerformed
        actionVenderAnimal(this);
    }//GEN-LAST:event_mnuVenderAnimalActionPerformed

    private void mnuResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuResumenActionPerformed
        actionResumenDiario(this);
    }//GEN-LAST:event_mnuResumenActionPerformed


    public static boolean actionSalir(Window inWin) {

        Window parent = inWin.getOwner();

        if (parent != null) {
            inWin.setVisible(false);
            inWin.dispose();
            parent.setVisible(true);
        } else {
            System.exit(0);
        }

        return true;
    }


    public static void actionVenderAnimal(java.awt.Window inaThis) {
        java.awt.EventQueue.invokeLater(() -> {
            new DlgVenderAnimal(inaThis).setVisible(true);
        });
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAppMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuResumen;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVenderAnimal;
    // End of variables declaration//GEN-END:variables


    private void actionResumenDiario(java.awt.Window inaThis) {
        java.awt.EventQueue.invokeLater(() -> {
            new DlgControlVentas(inaThis).setVisible(true);
        });
    }
}
