/*
 * Todos los derechos reservados por CAPIP Sistemas C.A., Venezuela
 * RIF J-407111787
 * capipsistemas@gmail.com, baba.orere@gmail.com
 * @2016, 2017, 2018
 */
package com.principal.reportes;

import com.principal.bancos.BancosChAnuReport;
import com.principal.capipsistema.FrmPrincipal;
import com.principal.capipsistema.Globales;
import com.principal.capipsistema.Propiedades;
import com.principal.capipsistema.UserPassIn;
import com.principal.capipsistema.UserTrack;
import com.principal.causados.CausadoReport;
import com.principal.compromisos.CompromisoReport;
import com.principal.connection.ConnCapip;
import com.principal.impuestos.ISLR_Rend;
import com.principal.impuestos.IVA_Rend;
import com.principal.impuestos.ImpMun_Rend;
import com.principal.impuestos.NegPri_Rend;
import com.principal.impuestos.ORet_Rend;
import com.principal.modelos.UserModel;
import com.principal.pagos.FondoAvanceEfectivoReport;
import com.principal.pagos.PagoReport;
import com.principal.presupuesto.PptoEjecucionMonthReport;
import com.principal.presupuesto.PptoEjecucionMonthReportII;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Formulario para la selección de reportes
 *
 * @author CAPIP Sistemas C.A.
 */
public class ReporteSel extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private final java.awt.Window parent;

    /**
     * Formulario para la selección de reportes
     *
     * @param inparent
     */
    public ReporteSel(final java.awt.Window inparent) {
        super();
        initComponents();
        parent = inparent;
        setOwnBehavior();
        setCompBehavior();
        setStartConditions();
    }

    /**
     * Rev 25/12/2016
     */
    private void setOwnBehavior() {
        setTitle(getTitle() + " - " + Propiedades.CAPIP_CLIENTE_RAZONSOCIAL);
        try {
            UserTrack.trackUser(getClass().getName(), "INIT", getTitle());
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
            logger.error(inex);
        }
        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                btnSalir.doClick();
            }
        });
    }

    /**
     * Rev 25/12/2016
     */
    private void setCompBehavior() {
    }

    /**
     * Rev 25/12/2016
     */
    private void setStartConditions() {
    }

    /**
     * Para Reubicar la ventana al ser visualizada Rev 25/09/2016
     *
     * @param inb
     */
    @Override
    public void setVisible(boolean inb) {
        // Para mostrar la ventana en el tope de la pantalla
        if (inb) {
            setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) / 2, 10);
        }
        super.setVisible(inb);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPartidasIng = new javax.swing.JButton();
        btnPartidasEgr = new javax.swing.JButton();
        btnCreAdiSumary = new javax.swing.JButton();
        btnComprSumary = new javax.swing.JButton();
        btnCauSummary = new javax.swing.JButton();
        btnPagoSummary = new javax.swing.JButton();
        btnIVA_Rend = new javax.swing.JButton();
        btnIslr_Rend = new javax.swing.JButton();
        btnImpMun_Rend = new javax.swing.JButton();
        btnNegPri_Rend = new javax.swing.JButton();
        btnAdelantoEfectivo = new javax.swing.JButton();
        btnChAnu = new javax.swing.JButton();
        btnTransPart = new javax.swing.JButton();
        btnORet_Rend = new javax.swing.JButton();
        btnExecMonthPpto = new javax.swing.JButton();
        btnExecAcumPpto = new javax.swing.JButton();
        btnExecMonthPptoII = new javax.swing.JButton();
        btnComprAnu = new javax.swing.JButton();
        btnCauAnu = new javax.swing.JButton();
        btnPagoAnu = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("REPORTES");
        setMinimumSize(new java.awt.Dimension(500, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));
        // NOI18N
        jLabel1.setFont(new java.awt.Font("Arial", 3, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCIONE EL TIPO DE REPORTE");
        jLabel1.setAlignmentX(0.5F);
        jPanel2.add(jLabel1);
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 450));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        // NOI18N
        btnPartidasIng.setFont(new java.awt.Font("Arial", 2, 14));
        btnPartidasIng.setText("PARTIDAS INGRESO");
        btnPartidasIng.setAlignmentX(0.5F);
        btnPartidasIng.setMaximumSize(new java.awt.Dimension(200, 30));
        btnPartidasIng.setMinimumSize(new java.awt.Dimension(200, 30));
        btnPartidasIng.setPreferredSize(new java.awt.Dimension(200, 30));
        btnPartidasIng.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidasIngActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnPartidasIng, gridBagConstraints);
        // NOI18N
        btnPartidasEgr.setFont(new java.awt.Font("Arial", 2, 14));
        btnPartidasEgr.setText("PARTIDAS EGRESO");
        btnPartidasEgr.setAlignmentX(0.5F);
        btnPartidasEgr.setMaximumSize(new java.awt.Dimension(200, 30));
        btnPartidasEgr.setMinimumSize(new java.awt.Dimension(200, 30));
        btnPartidasEgr.setPreferredSize(new java.awt.Dimension(200, 30));
        btnPartidasEgr.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidasEgrActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnPartidasEgr, gridBagConstraints);
        // NOI18N
        btnCreAdiSumary.setFont(new java.awt.Font("Arial", 2, 14));
        btnCreAdiSumary.setText("CREDITO ADICIONAL");
        btnCreAdiSumary.setAlignmentX(0.5F);
        btnCreAdiSumary.setMaximumSize(new java.awt.Dimension(200, 30));
        btnCreAdiSumary.setMinimumSize(new java.awt.Dimension(200, 30));
        btnCreAdiSumary.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCreAdiSumary.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreAdiSumaryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnCreAdiSumary, gridBagConstraints);
        // NOI18N
        btnComprSumary.setFont(new java.awt.Font("Arial", 2, 14));
        btnComprSumary.setText("COMPROMISO");
        btnComprSumary.setAlignmentX(0.5F);
        btnComprSumary.setMaximumSize(new java.awt.Dimension(200, 30));
        btnComprSumary.setMinimumSize(new java.awt.Dimension(200, 30));
        btnComprSumary.setPreferredSize(new java.awt.Dimension(200, 30));
        btnComprSumary.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprSumaryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnComprSumary, gridBagConstraints);
        // NOI18N
        btnCauSummary.setFont(new java.awt.Font("Arial", 2, 14));
        btnCauSummary.setText("CAUSADO");
        btnCauSummary.setAlignmentX(0.5F);
        btnCauSummary.setMaximumSize(new java.awt.Dimension(200, 30));
        btnCauSummary.setMinimumSize(new java.awt.Dimension(200, 30));
        btnCauSummary.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCauSummary.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauSummaryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnCauSummary, gridBagConstraints);
        // NOI18N
        btnPagoSummary.setFont(new java.awt.Font("Arial", 2, 14));
        btnPagoSummary.setText("PAGO");
        btnPagoSummary.setAlignmentX(0.5F);
        btnPagoSummary.setMaximumSize(new java.awt.Dimension(200, 30));
        btnPagoSummary.setMinimumSize(new java.awt.Dimension(200, 30));
        btnPagoSummary.setPreferredSize(new java.awt.Dimension(200, 30));
        btnPagoSummary.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoSummaryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnPagoSummary, gridBagConstraints);
        // NOI18N
        btnIVA_Rend.setFont(new java.awt.Font("Arial", 2, 14));
        btnIVA_Rend.setText("RENDICIÓN IVA");
        btnIVA_Rend.setAlignmentX(0.5F);
        btnIVA_Rend.setMaximumSize(new java.awt.Dimension(200, 30));
        btnIVA_Rend.setMinimumSize(new java.awt.Dimension(200, 30));
        btnIVA_Rend.setPreferredSize(new java.awt.Dimension(200, 30));
        btnIVA_Rend.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIVA_RendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnIVA_Rend, gridBagConstraints);
        // NOI18N
        btnIslr_Rend.setFont(new java.awt.Font("Arial", 2, 14));
        btnIslr_Rend.setText("RENDICIÓN ISLR");
        btnIslr_Rend.setAlignmentX(0.5F);
        btnIslr_Rend.setMaximumSize(new java.awt.Dimension(200, 30));
        btnIslr_Rend.setMinimumSize(new java.awt.Dimension(200, 30));
        btnIslr_Rend.setPreferredSize(new java.awt.Dimension(200, 30));
        btnIslr_Rend.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIslr_RendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnIslr_Rend, gridBagConstraints);
        // NOI18N
        btnImpMun_Rend.setFont(new java.awt.Font("Arial", 2, 14));
        btnImpMun_Rend.setText("RENDICIÓN IMP.1.x.10.");
        btnImpMun_Rend.setAlignmentX(0.5F);
        btnImpMun_Rend.setMaximumSize(new java.awt.Dimension(200, 30));
        btnImpMun_Rend.setMinimumSize(new java.awt.Dimension(200, 30));
        btnImpMun_Rend.setPreferredSize(new java.awt.Dimension(200, 30));
        btnImpMun_Rend.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpMun_RendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnImpMun_Rend, gridBagConstraints);
        // NOI18N
        btnNegPri_Rend.setFont(new java.awt.Font("Arial", 2, 14));
        btnNegPri_Rend.setText("RENDICIÓN NEGRO PRIMERO");
        btnNegPri_Rend.setAlignmentX(0.5F);
        btnNegPri_Rend.setMaximumSize(new java.awt.Dimension(200, 30));
        btnNegPri_Rend.setMinimumSize(new java.awt.Dimension(200, 30));
        btnNegPri_Rend.setPreferredSize(new java.awt.Dimension(200, 30));
        btnNegPri_Rend.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegPri_RendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnNegPri_Rend, gridBagConstraints);
        // NOI18N
        btnAdelantoEfectivo.setFont(new java.awt.Font("Arial", 2, 14));
        btnAdelantoEfectivo.setText("FONDO AVANCE");
        btnAdelantoEfectivo.setAlignmentX(0.5F);
        btnAdelantoEfectivo.setMaximumSize(new java.awt.Dimension(200, 30));
        btnAdelantoEfectivo.setMinimumSize(new java.awt.Dimension(200, 30));
        btnAdelantoEfectivo.setPreferredSize(new java.awt.Dimension(200, 30));
        btnAdelantoEfectivo.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelantoEfectivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnAdelantoEfectivo, gridBagConstraints);
        // NOI18N
        btnChAnu.setFont(new java.awt.Font("Arial", 2, 14));
        btnChAnu.setText("CHEQUE ANULADO");
        btnChAnu.setAlignmentX(0.5F);
        btnChAnu.setMaximumSize(new java.awt.Dimension(200, 30));
        btnChAnu.setMinimumSize(new java.awt.Dimension(200, 30));
        btnChAnu.setPreferredSize(new java.awt.Dimension(200, 30));
        btnChAnu.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChAnuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnChAnu, gridBagConstraints);
        // NOI18N
        btnTransPart.setFont(new java.awt.Font("Arial", 2, 14));
        btnTransPart.setText("TRASPASO PARTIDAS");
        btnTransPart.setAlignmentX(0.5F);
        btnTransPart.setMaximumSize(new java.awt.Dimension(200, 30));
        btnTransPart.setMinimumSize(new java.awt.Dimension(200, 30));
        btnTransPart.setPreferredSize(new java.awt.Dimension(200, 30));
        btnTransPart.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransPartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnTransPart, gridBagConstraints);
        // NOI18N
        btnORet_Rend.setFont(new java.awt.Font("Arial", 2, 14));
        btnORet_Rend.setText("RENDICIÓN OTRAS RET.");
        btnORet_Rend.setAlignmentX(0.5F);
        btnORet_Rend.setMaximumSize(new java.awt.Dimension(200, 30));
        btnORet_Rend.setMinimumSize(new java.awt.Dimension(200, 30));
        btnORet_Rend.setPreferredSize(new java.awt.Dimension(200, 30));
        btnORet_Rend.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnORet_RendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnORet_Rend, gridBagConstraints);
        // NOI18N
        btnExecMonthPpto.setFont(new java.awt.Font("Arial", 2, 14));
        btnExecMonthPpto.setText("EJEC. MENSUAL PPTO.");
        btnExecMonthPpto.setAlignmentX(0.5F);
        btnExecMonthPpto.setMaximumSize(new java.awt.Dimension(200, 30));
        btnExecMonthPpto.setMinimumSize(new java.awt.Dimension(200, 30));
        btnExecMonthPpto.setPreferredSize(new java.awt.Dimension(200, 30));
        btnExecMonthPpto.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecMonthPptoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnExecMonthPpto, gridBagConstraints);
        // NOI18N
        btnExecAcumPpto.setFont(new java.awt.Font("Arial", 2, 14));
        btnExecAcumPpto.setText("EJEC. ACUM. PPTO.");
        btnExecAcumPpto.setAlignmentX(0.5F);
        btnExecAcumPpto.setEnabled(false);
        btnExecAcumPpto.setMaximumSize(new java.awt.Dimension(200, 30));
        btnExecAcumPpto.setMinimumSize(new java.awt.Dimension(200, 30));
        btnExecAcumPpto.setPreferredSize(new java.awt.Dimension(200, 30));
        btnExecAcumPpto.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecAcumPptoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnExecAcumPpto, gridBagConstraints);
        // NOI18N
        btnExecMonthPptoII.setFont(new java.awt.Font("Arial", 2, 14));
        btnExecMonthPptoII.setText("EJEC. MENSUAL PPTO. II");
        btnExecMonthPptoII.setActionCommand("EJEC. ACUM. PPTO.");
        btnExecMonthPptoII.setAlignmentX(0.5F);
        btnExecMonthPptoII.setMaximumSize(new java.awt.Dimension(200, 30));
        btnExecMonthPptoII.setMinimumSize(new java.awt.Dimension(200, 30));
        btnExecMonthPptoII.setPreferredSize(new java.awt.Dimension(200, 30));
        btnExecMonthPptoII.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecMonthPptoIIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnExecMonthPptoII, gridBagConstraints);
        // NOI18N
        btnComprAnu.setFont(new java.awt.Font("Arial", 2, 14));
        btnComprAnu.setText("COMPROMISO. II");
        btnComprAnu.setAlignmentX(0.5F);
        btnComprAnu.setEnabled(false);
        btnComprAnu.setMaximumSize(new java.awt.Dimension(200, 30));
        btnComprAnu.setMinimumSize(new java.awt.Dimension(200, 30));
        btnComprAnu.setPreferredSize(new java.awt.Dimension(200, 30));
        btnComprAnu.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprAnuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnComprAnu, gridBagConstraints);
        // NOI18N
        btnCauAnu.setFont(new java.awt.Font("Arial", 2, 14));
        btnCauAnu.setText("CAUSADO II");
        btnCauAnu.setAlignmentX(0.5F);
        btnCauAnu.setEnabled(false);
        btnCauAnu.setMaximumSize(new java.awt.Dimension(200, 30));
        btnCauAnu.setMinimumSize(new java.awt.Dimension(200, 30));
        btnCauAnu.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCauAnu.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauAnuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnCauAnu, gridBagConstraints);
        // NOI18N
        btnPagoAnu.setFont(new java.awt.Font("Arial", 2, 14));
        btnPagoAnu.setText("PAGO II");
        btnPagoAnu.setAlignmentX(0.5F);
        btnPagoAnu.setEnabled(false);
        btnPagoAnu.setMaximumSize(new java.awt.Dimension(200, 30));
        btnPagoAnu.setMinimumSize(new java.awt.Dimension(200, 30));
        btnPagoAnu.setPreferredSize(new java.awt.Dimension(200, 30));
        btnPagoAnu.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoAnuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(btnPagoAnu, gridBagConstraints);
        jPanel2.add(jPanel1);
        btnSalir.setBackground(new java.awt.Color(153, 153, 0));
        // NOI18N
        btnSalir.setFont(new java.awt.Font("Arial", 3, 14));
        btnSalir.setText("SALIR");
        btnSalir.setAlignmentX(0.5F);
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSalir.setMaximumSize(new java.awt.Dimension(100, 40));
        btnSalir.setMinimumSize(new java.awt.Dimension(100, 40));
        btnSalir.setPreferredSize(new java.awt.Dimension(100, 40));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 510));
        // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo azul 22.png")));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 530, 540));
        pack();
        setLocationRelativeTo(null);
    }

    // </editor-fold>//GEN-END:initComponents
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnSalirActionPerformed
        actSalir();
    }

//GEN-LAST:event_btnSalirActionPerformed
    private void btnComprSumaryActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnComprSumaryActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new CompromisoReport(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnComprSumaryActionPerformed
    private void btnCauSummaryActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnCauSummaryActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new CausadoReport(me).setVisible(true);
                me.setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnCauSummaryActionPerformed
    private void btnPagoSummaryActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnPagoSummaryActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PagoReport(me).setVisible(true);
                me.setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnPagoSummaryActionPerformed
    private void btnIVA_RendActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnIVA_RendActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new IVA_Rend(me).setVisible(true);
                me.setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnIVA_RendActionPerformed
    private void btnCreAdiSumaryActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnCreAdiSumaryActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new CreditoAdicionalReport(me).setVisible(true);
                me.setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnCreAdiSumaryActionPerformed
    private void btnAdelantoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnAdelantoEfectivoActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FondoAvanceEfectivoReport(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnAdelantoEfectivoActionPerformed
    private void btnChAnuActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnChAnuActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new BancosChAnuReport(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnChAnuActionPerformed
    private void btnPartidasIngActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnPartidasIngActionPerformed
        final long ejeFis;
        try {
            ejeFis = Globales.getEjeFisYear();
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
            logger.error(inex);
            return;
        }
        final Map<String, Object> param = new HashMap<>(101);
        param.put("ejefis", ejeFis);
        param.put("ejefismes_desde", ejeFis * 100 + 1);
        param.put("ejefismes_hasta", ejeFis * 100 + 12);
        param.put("mesdesde", 1);
        param.put("meshasta", 12);
        param.put("fechahoy", Globales.dateFormat.format(Globales.getServerTimeStamp()));
        param.put("iduser", UserPassIn.getIdUser());
        param.put("idsession", UserPassIn.getIdSession());
        param.put("user", UserPassIn.getIdUser() <= 0 ? "DEBUG" : UserModel.getUser(UserPassIn.getIdUser()));
        param.put("rpt_fecha_hora", Globales.getServerTimeStamp());
        param.put("aux_1", Propiedades.CAPIP_AUX_1);
        param.put("aux_2", Propiedades.CAPIP_AUX_2);
        param.put("linea_1", Propiedades.CAPIP_LINEA_1);
        param.put("linea_2", Propiedades.CAPIP_LINEA_2);
        param.put("linea_3", Propiedades.CAPIP_LINEA_3);
        param.put("linea_4", Propiedades.CAPIP_LINEA_4);
        final Class aClass = FrmPrincipal.getInstance().getClass();
        param.put("logo_iz", aClass.getResourceAsStream("/imagenes/logo_iz.png"));
        param.put("logo_der", aClass.getResourceAsStream("/imagenes/logo_der.png"));
        final InputStream pathRpt = aClass.getResourceAsStream("/reportes/partidasIngRptSummary.jasper");
        if (pathRpt != null) {
            new Thread() {

                @Override
                public void run() {
                    try {
                        JasperViewer.viewReport(JasperFillManager.fillReport(pathRpt, new HashMap<>(param), cn), false);
                    } catch (final Exception inex) {
                        JOptionPane.showMessageDialog(null, inex);
                        logger.error(inex);
                    }
                }
            }.start();
        } else {
            JOptionPane.showMessageDialog(null, "Reporte sumario no encontrado");
        }
    }

//GEN-LAST:event_btnPartidasIngActionPerformed
    private void btnPartidasEgrActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnPartidasEgrActionPerformed
        final long ejeFis;
        try {
            ejeFis = Globales.getEjeFisYear();
        } catch (final Exception inex) {
            JOptionPane.showMessageDialog(null, inex);
            logger.error(inex);
            return;
        }
        final Map<String, Object> param = new HashMap<>(101);
        param.put("ejefis", ejeFis);
        param.put("ejefismes_desde", ejeFis * 100 + 1);
        param.put("ejefismes_hasta", ejeFis * 100 + 12);
        param.put("mesdesde", 1);
        param.put("meshasta", 12);
        param.put("fechahoy", Globales.dateFormat.format(Globales.getServerTimeStamp()));
        param.put("iduser", UserPassIn.getIdUser());
        param.put("idsession", UserPassIn.getIdSession());
        param.put("user", UserPassIn.getIdUser() <= 0 ? "DEBUG" : UserModel.getUser(UserPassIn.getIdUser()));
        param.put("rpt_fecha_hora", Globales.getServerTimeStamp());
        param.put("aux_1", Propiedades.CAPIP_AUX_1);
        param.put("aux_2", Propiedades.CAPIP_AUX_2);
        param.put("linea_1", Propiedades.CAPIP_LINEA_1);
        param.put("linea_2", Propiedades.CAPIP_LINEA_2);
        param.put("linea_3", Propiedades.CAPIP_LINEA_3);
        param.put("linea_4", Propiedades.CAPIP_LINEA_4);
        final Class aClass = FrmPrincipal.getInstance().getClass();
        param.put("logo_iz", aClass.getResourceAsStream("/imagenes/logo_iz.png"));
        param.put("logo_der", aClass.getResourceAsStream("/imagenes/logo_der.png"));
        final InputStream pathRpt = aClass.getResourceAsStream("/reportes/partidasEgrRptSummary.jasper");
        if (pathRpt != null) {
            new Thread() {

                @Override
                public void run() {
                    try {
                        JasperViewer.viewReport(JasperFillManager.fillReport(pathRpt, new HashMap<>(param), cn), false);
                    } catch (final Exception inex) {
                        JOptionPane.showMessageDialog(null, inex);
                        logger.error(inex);
                    }
                }
            }.start();
        } else {
            JOptionPane.showMessageDialog(null, "Reporte sumario no encontrado");
        }
    }

//GEN-LAST:event_btnPartidasEgrActionPerformed
    private void btnTransPartActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnTransPartActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new TraspPartReport(me).setVisible(true);
            }
        });
        setVisible(false);
    }

//GEN-LAST:event_btnTransPartActionPerformed
    private void btnIslr_RendActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnIslr_RendActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ISLR_Rend(me).setVisible(true);
                me.setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnIslr_RendActionPerformed
    private void btnORet_RendActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnORet_RendActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ORet_Rend(me).setVisible(true);
                me.setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnORet_RendActionPerformed
    private void btnExecMonthPptoActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnExecMonthPptoActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PptoEjecucionMonthReport(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnExecMonthPptoActionPerformed
    private void btnExecAcumPptoActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnExecAcumPptoActionPerformed
        // TODO add your handling code here:
    }

//GEN-LAST:event_btnExecAcumPptoActionPerformed
    private void btnExecMonthPptoIIActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnExecMonthPptoIIActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PptoEjecucionMonthReportII(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnExecMonthPptoIIActionPerformed
    private void btnImpMun_RendActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnImpMun_RendActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ImpMun_Rend(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnImpMun_RendActionPerformed
    private void btnNegPri_RendActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnNegPri_RendActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NegPri_Rend(me).setVisible(true);
                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnNegPri_RendActionPerformed
    private void btnComprAnuActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnComprAnuActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //                new CompromisoReport(me).setVisible(true);
                //                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnComprAnuActionPerformed
    private void btnCauAnuActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnCauAnuActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //                new CompromisoReport(me).setVisible(true);
                ////                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnCauAnuActionPerformed
    private void btnPagoAnuActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnPagoAnuActionPerformed
        final java.awt.Window me = this;
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //                new CompromisoReport(me).setVisible(true);
                //                setVisible(false);
            }
        });
    }

//GEN-LAST:event_btnPagoAnuActionPerformed
    /**
     * Rev 06/11/2016
     */
    private void actSalir() {
        if (parent != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    parent.setVisible(true);
                    dispose();
                }
            });
        } else {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ReporteSel(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdelantoEfectivo;

    private javax.swing.JButton btnCauAnu;

    private javax.swing.JButton btnCauSummary;

    private javax.swing.JButton btnChAnu;

    private javax.swing.JButton btnComprAnu;

    private javax.swing.JButton btnComprSumary;

    private javax.swing.JButton btnCreAdiSumary;

    private javax.swing.JButton btnExecAcumPpto;

    private javax.swing.JButton btnExecMonthPpto;

    private javax.swing.JButton btnExecMonthPptoII;

    private javax.swing.JButton btnIVA_Rend;

    private javax.swing.JButton btnImpMun_Rend;

    private javax.swing.JButton btnIslr_Rend;

    private javax.swing.JButton btnNegPri_Rend;

    private javax.swing.JButton btnORet_Rend;

    private javax.swing.JButton btnPagoAnu;

    private javax.swing.JButton btnPagoSummary;

    private javax.swing.JButton btnPartidasEgr;

    private javax.swing.JButton btnPartidasIng;

    private javax.swing.JButton btnSalir;

    private javax.swing.JButton btnTransPart;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    // End of variables declaration//GEN-END:variables
    private final Connection cn = ConnCapip.getInstance().getConnection();

    private static final Logger logger = LogManager.getLogger(ReporteSel.class);
}
