package bancos;

import capipsistema.CapipPropiedades;
import capipsistema.Conn;
import capipsistema.Globales;
import capipsistema.UserPassIn;
import capipsistema.UserTrack;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import utils.Format;

/**
 *
 * @author CAPIP Sistemas C.A.
 */
public final class BancosCuentasRegistro extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private final java.awt.Window parent;

    /**
     * Creates new form rcuentas
     *
     * @param _parent
     */
    public BancosCuentasRegistro(final java.awt.Window _parent) {

        super();
        initComponents();

        parent = _parent;

        setOwnBehavior();
        setCompBehavior();
        setStartConditions();
    }

    /**
     * Para Reubicar la ventana al ser visualizada
     *
     * @param _b
     */
    @Override
    public void setVisible(boolean _b) {
        // Para mostrar la ventana en el tope de la pantalla
        if (_b) {
            setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) / 2, 10);
        }

        super.setVisible(_b);
    }

    /**
     * Establece el comportamiento de la presente Ventana
     * Rev 21/09/2016
     *
     */
    private void setOwnBehavior() {
        try {
            UserTrack.trackUser(getClass().getName(), "INIT", getTitle());
        } catch (final Exception _ex) {
            JOptionPane.showMessageDialog(null, _ex);
        }

        setTitle(CapipPropiedades.CAPIP_SISTEMAS + " - " + getTitle() + " - " + CapipPropiedades.CAPIP_CLIENTE_RAZONSOCIAL);

        // Establecer acción al cerrar ventana
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                actSalir();
            }
        });

        // Para salir con la tecla ESC
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");

        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                actSalir();
            }
        });

    }

    /**
     * Rev /10/2016
     */
    private void setCompBehavior() {
    }

    /**
     * Rev /10/2016
     */
    private void setStartConditions() {
        txtFecha.setText(fechaActual());
    }

    private void limpiar() {
        txtBanco.setText("");
        txtCuenta.setText("");
        txtSaldo.setText("");
    }

    public static String fechaActual() {
        return new SimpleDateFormat("dd/MM/YYYY").format(Globales.getServerTimeStamp());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        txtSaldo = new javax.swing.JFormattedTextField();
        txtCuenta = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel16.setText("FECHA:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("REGISTRO DE CUENTAS BANCARIAS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(java.awt.SystemColor.inactiveCaption);
        btnSalir.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 230, 110, 40));

        btnGuardar.setBackground(java.awt.SystemColor.inactiveCaption);
        btnGuardar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 106, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("NOMBRE DEL BANCO ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("       DATOS DE LA CUENTA BANCARIA A REGISTRAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 491, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("NUMERO DE CUENTA BANCARIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 243, -1));

        txtBanco.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtBanco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBanco.setSelectionColor(new java.awt.Color(175, 204, 125));
        txtBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBancoActionPerformed(evt);
            }
        });
        getContentPane().add(txtBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 230, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("SALDO INICIAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel15.setText("FECHA ACTUAL");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtFecha.setSelectionColor(new java.awt.Color(175, 204, 125));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 30));

        txtSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaldo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtSaldo.setSelectionColor(new java.awt.Color(175, 204, 125));
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 240, 30));

        txtCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCuenta.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtCuenta.setSelectionColor(new java.awt.Color(175, 204, 125));
        txtCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo azul 22.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        actSalir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        txtBanco.requestFocus();

        final String banco = txtBanco.getText().trim().toUpperCase();
        if (banco.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe indicar el Banco");
            txtBanco.requestFocusInWindow();
            return;
        }

        final String cuenta = txtCuenta.getText().trim().toUpperCase();
        if (cuenta.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe indicar una Cuenta");
            txtCuenta.requestFocusInWindow();
            return;
        }

        if (cuenta.length() != 20) {
            JOptionPane.showMessageDialog(null, "Longitud de la Cuenta inválida");
            txtSaldo.requestFocusInWindow();
            return;
        }

        final String sSaldo = txtSaldo.getText().trim().toUpperCase();
        if (sSaldo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe indicar el saldo inicial");
            txtSaldo.requestFocusInWindow();
            return;
        }

        final double saldo;

        try {
            saldo = (Double) Globales.curFormat.stringToValue(sSaldo);
        } catch (final Exception _ex) {
            JOptionPane.showMessageDialog(null, "Saldo inicial inválido");
            txtSaldo.requestFocusInWindow();
            return;
        }

        final Calendar fechaOp = Calendar.getInstance();
        final long ejeFis = fechaOp.get(Calendar.YEAR);
        final long ejeFisMes = ejeFis * 100 + fechaOp.get(Calendar.MONTH) + 1;

        try {
            Conn.BeginTransaction();

            final PreparedStatement pstBancos = Conn.getConnection().prepareStatement("INSERT INTO bancos("
                + "cuenta, banco, saldoi, ejefis, ejefismes, iduser) "
                + "VALUES (?, ?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
            pstBancos.setString(1, cuenta);
            pstBancos.setString(2, banco);
            pstBancos.setDouble(3, saldo);
            pstBancos.setLong(4, ejeFis);
            pstBancos.setLong(5, ejeFisMes);
            pstBancos.setLong(6, UserPassIn.getIdUser());
            if (pstBancos.executeUpdate() != 1) {
                throw new Exception("Eror al tratar de insertar el registro");
            }

            // Toma el ultimo id generado
            final long id_banco;
            final ResultSet rsId = pstBancos.getGeneratedKeys();
            if (rsId.next()) {
                id_banco = rsId.getLong(1);
            } else {
                throw new Exception("Error al tratar de recupera el ID");
            }

            // Generar el registro anual del Banco
            final PreparedStatement pst = Conn.getConnection().prepareStatement("INSERT INTO banco_saldo_anual("
                + "id_user, id_session, " // 1, 2
                + "date_session, ejefis, " // 3, 4, 
                + "id_banco, saldoi) " // 5, 6
                + "VALUES (?, ?, ?, ?, ?, ?)");
            pst.setLong(1, UserPassIn.getIdUser()); // id_user
            pst.setLong(2, UserPassIn.getIdSession()); // id_session
            pst.setTimestamp(3, UserPassIn.getDateSession());
            pst.setDate(4, Globales.getEjefis()); // ejefis
            pst.setLong(5, id_banco);
            pst.setBigDecimal(6, Format.toBigDec(saldo));
            if (pst.executeUpdate() != 1) {
                throw new Exception("Error al insertar el registro");
            }

            final PreparedStatement pstSecuencial = Conn.getConnection().prepareStatement("INSERT INTO map_next_id"
                + "(clave, valor, id_user) "
                + "VALUES (?, ?, ?)");
            pstSecuencial.setString(1, Globales.getEjeFisYear() + "-" + cuenta);
            pstSecuencial.setInt(2, 0);
            pstSecuencial.setLong(3, UserPassIn.getIdUser());
            if (pstSecuencial.executeUpdate() != 1) {
                throw new Exception("Eror al tratar de insertar el registro");
            }

            Conn.EndTransaction();

            JOptionPane.showMessageDialog(null, "Los datos se guardaron correctamente");
            limpiar();

        } catch (final Exception _ex) {
            JOptionPane.showMessageDialog(null, _ex);
            try {
                Conn.RollBack();
            } catch (final Exception _ex1) {
                JOptionPane.showMessageDialog(null, _ex1);
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoActionPerformed
        txtBanco.transferFocus();
    }//GEN-LAST:event_txtBancoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        txtFecha.transferFocus();
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txtCuenta.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuentaKeyTyped

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        btnGuardar.requestFocusInWindow();
    }//GEN-LAST:event_txtSaldoActionPerformed

    /**
     * Rev 25/11/2016
     *
     */
    private void actSalir() {
        if (parent != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    parent.setVisible(true);
                    dispose();
                }
            });
        } else {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new BancosCuentasRegistro(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JFormattedTextField txtCuenta;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtSaldo;
    // End of variables declaration//GEN-END:variables

    Connection cn = Conn.getConnection();
}
